### ISSUE TITLE
Polls are not working for unregisterd users on Owncloud

### ISSUE THREAD

**Issue by WHGhost** [nextcloud/polls#448] opened 2018-12-16 18:02 UTC
### Public polls are not working on Owncloud

On Owncloud, the poll page keeps refreshing itself when visited as not logged in users as they do not have the permission to see people's avatar, which causes Owncloud to consider that something went wrong in the page's loading.

**To Reproduce**
Create a public or hidden poll as a logged-in user, then log out and visit the link. The page keeps refreshing every 5 seconds, which make it unusable.

**Expected behavior**
The page should not try to load avatars which can't be accessed by the current user.

**Version:** 0.8.1, installed from Owncloud 10.0.10.4 appstore.

**Comment by dartcafe** [comment] 2018-12-16 21:46
Duplicate of #344. 0.8.2 didn't make it to the owncloud store.

**Closed by dartcafe** 2018-12-16 21:46 UTC
Labels: duplicate
