### ISSUE TITLE
Error managing users groups when polls enabled

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/polls#3047] opened 2023-09-02 10:43 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Whenever I enable poll, I get an error when adding users to groups or removing them from a group. However, the error just prevents from sending email notifications, nothing else.

Also, there appear errors in the log. The cron-job also get the same error.

From what I read from the error, it seems to be an issue with `OC\Activity\Manager->getProviders()`. Looks like Polls has such a notification provider and that brings up the error somehow.

As soon as I disable the polls app, the error is gone.

### What did you expect, how polls should behave instead?

The error should not appear when adding/removing groups on a user. The error also should not appear when the cron-job executes.

### What steps does it need to replay this bug?

1. Enable Polls
2. Try adding a user to a group. (Beware, this does not happen for all users, not sure why, didn't find the problem.)

### Installation method

Installed/updated via extracting downloaded package to the apps folder

### Installation type

First time installation

### Affected polls version

5.3.0-beta1

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Additional client environment information

Windows 11 Pro (x86_64)

### NC version

Nextcloud 27 (Nextcloud Hub 5)

### PHP engine version

Other/Don't know

### Other PHP version

8.2

### Database engine

MySQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
ubuntu@dcloud:~$ sudo nextcloud.occ group:adduser admin weicjas -vvv

In SimpleContainer.php line 110:

  [OCP\AppFramework\QueryException]
  Could not resolve OCP\Activity\IEvent! Class can not be instantiated


Exception trace:
  at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:110
 OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}() at n/a:n/a
 array_map() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:116
 OC\AppFramework\Utility\SimpleContainer->buildClass() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:124
 OC\AppFramework\Utility\SimpleContainer->resolve() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:142
 OC\AppFramework\Utility\SimpleContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/ServerContainer.php:171
 OC\ServerContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/Activity/Manager.php:245
 OC\Activity\Manager->getProviders() at /snap/nextcloud/37046/htdocs/apps/activity/lib/NotificationGenerator.php:94
 OCA\Activity\NotificationGenerator->populateEvent() at /snap/nextcloud/37046/htdocs/apps/activity/lib/NotificationGenerator.php:123
 OCA\Activity\NotificationGenerator->prepare() at /snap/nextcloud/37046/htdocs/lib/private/Notification/Manager.php:368
 OC\Notification\Manager->prepare() at /snap/nextcloud/37046/htdocs/apps/notifications/lib/Push.php:304
 OCA\Notifications\Push->pushToDevice() at /snap/nextcloud/37046/htdocs/apps/notifications/lib/App.php:58
 OCA\Notifications\App->notify() at /snap/nextcloud/37046/htdocs/lib/private/Notification/Manager.php:329
 OC\Notification\Manager->notify() at /snap/nextcloud/37046/htdocs/apps/activity/lib/NotificationGenerator.php:61
 OCA\Activity\NotificationGenerator->sendNotificationForEvent() at /snap/nextcloud/37046/htdocs/apps/activity/lib/Consumer.php:71
 OCA\Activity\Consumer->receive() at /snap/nextcloud/37046/htdocs/lib/private/Activity/Manager.php:157
 OC\Activity\Manager->publish() at /snap/nextcloud/37046/htdocs/apps/settings/lib/Listener/UserAddedToGroupActivityListener.php:92
 OCA\Settings\Listener\UserAddedToGroupActivityListener->handle() at /snap/nextcloud/37046/htdocs/lib/private/EventDispatcher/ServiceEventListener.php:86
 OC\EventDispatcher\ServiceEventListener->__invoke() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php:251
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php:73
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /snap/nextcloud/37046/htdocs/lib/private/EventDispatcher/EventDispatcher.php:94
 OC\EventDispatcher\EventDispatcher->dispatch() at /snap/nextcloud/37046/htdocs/lib/private/EventDispatcher/EventDispatcher.php:106
 OC\EventDispatcher\EventDispatcher->dispatchTyped() at /snap/nextcloud/37046/htdocs/lib/private/Server.php:527
 OC\Server->OC\{closure}() at n/a:n/a
 call_user_func_array() at /snap/nextcloud/37046/htdocs/lib/private/Hooks/EmitterTrait.php:105
 OC\Hooks\BasicEmitter->emit() at /snap/nextcloud/37046/htdocs/lib/private/Hooks/PublicEmitter.php:40
 OC\Hooks\PublicEmitter->emit() at /snap/nextcloud/37046/htdocs/lib/private/Group/Group.php:202
 OC\Group\Group->addUser() at /snap/nextcloud/37046/htdocs/core/Command/Group/AddUser.php:72
 OC\Core\Command\Group\AddUser->execute() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /snap/nextcloud/37046/htdocs/core/Command/Base.php:177
 OC\Core\Command\Base->run() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /snap/nextcloud/37046/htdocs/lib/private/Console/Application.php:211
 OC\Console\Application->run() at /snap/nextcloud/37046/htdocs/console.php:100
 require_once() at /snap/nextcloud/37046/htdocs/occ:11

In SimpleContainer.php line 110:

  [OCP\AppFramework\QueryException]
  Could not resolve OCP\Activity\IEvent! Class can not be instantiated


Exception trace:
  at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:110
 OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}() at n/a:n/a
 array_map() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:116
 OC\AppFramework\Utility\SimpleContainer->buildClass() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:124
 OC\AppFramework\Utility\SimpleContainer->resolve() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:142
 OC\AppFramework\Utility\SimpleContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/ServerContainer.php:171
 OC\ServerContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:97
 OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}() at n/a:n/a
 array_map() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:116
 OC\AppFramework\Utility\SimpleContainer->buildClass() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:124
 OC\AppFramework\Utility\SimpleContainer->resolve() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:142
 OC\AppFramework\Utility\SimpleContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/ServerContainer.php:171
 OC\ServerContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/Activity/Manager.php:245
 OC\Activity\Manager->getProviders() at /snap/nextcloud/37046/htdocs/apps/activity/lib/NotificationGenerator.php:94
 OCA\Activity\NotificationGenerator->populateEvent() at /snap/nextcloud/37046/htdocs/apps/activity/lib/NotificationGenerator.php:123
 OCA\Activity\NotificationGenerator->prepare() at /snap/nextcloud/37046/htdocs/lib/private/Notification/Manager.php:368
 OC\Notification\Manager->prepare() at /snap/nextcloud/37046/htdocs/apps/notifications/lib/Push.php:304
 OCA\Notifications\Push->pushToDevice() at /snap/nextcloud/37046/htdocs/apps/notifications/lib/App.php:58
 OCA\Notifications\App->notify() at /snap/nextcloud/37046/htdocs/lib/private/Notification/Manager.php:329
 OC\Notification\Manager->notify() at /snap/nextcloud/37046/htdocs/apps/activity/lib/NotificationGenerator.php:61
 OCA\Activity\NotificationGenerator->sendNotificationForEvent() at /snap/nextcloud/37046/htdocs/apps/activity/lib/Consumer.php:71
 OCA\Activity\Consumer->receive() at /snap/nextcloud/37046/htdocs/lib/private/Activity/Manager.php:157
 OC\Activity\Manager->publish() at /snap/nextcloud/37046/htdocs/apps/settings/lib/Listener/UserAddedToGroupActivityListener.php:92
 OCA\Settings\Listener\UserAddedToGroupActivityListener->handle() at /snap/nextcloud/37046/htdocs/lib/private/EventDispatcher/ServiceEventListener.php:86
 OC\EventDispatcher\ServiceEventListener->__invoke() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php:251
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php:73
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /snap/nextcloud/37046/htdocs/lib/private/EventDispatcher/EventDispatcher.php:94
 OC\EventDispatcher\EventDispatcher->dispatch() at /snap/nextcloud/37046/htdocs/lib/private/EventDispatcher/EventDispatcher.php:106
 OC\EventDispatcher\EventDispatcher->dispatchTyped() at /snap/nextcloud/37046/htdocs/lib/private/Server.php:527
 OC\Server->OC\{closure}() at n/a:n/a
 call_user_func_array() at /snap/nextcloud/37046/htdocs/lib/private/Hooks/EmitterTrait.php:105
 OC\Hooks\BasicEmitter->emit() at /snap/nextcloud/37046/htdocs/lib/private/Hooks/PublicEmitter.php:40
 OC\Hooks\PublicEmitter->emit() at /snap/nextcloud/37046/htdocs/lib/private/Group/Group.php:202
 OC\Group\Group->addUser() at /snap/nextcloud/37046/htdocs/core/Command/Group/AddUser.php:72
 OC\Core\Command\Group\AddUser->execute() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /snap/nextcloud/37046/htdocs/core/Command/Base.php:177
 OC\Core\Command\Base->run() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /snap/nextcloud/37046/htdocs/lib/private/Console/Application.php:211
 OC\Console\Application->run() at /snap/nextcloud/37046/htdocs/console.php:100
 require_once() at /snap/nextcloud/37046/htdocs/occ:11

In SimpleContainer.php line 126:

  [OCP\AppFramework\QueryException]
  Could not resolve OCP\Activity\IEvent! Class can not be instantiated


Exception trace:
  at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:126
 OC\AppFramework\Utility\SimpleContainer->resolve() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:142
 OC\AppFramework\Utility\SimpleContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/ServerContainer.php:171
 OC\ServerContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:97
 OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}() at n/a:n/a
 array_map() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:116
 OC\AppFramework\Utility\SimpleContainer->buildClass() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:124
 OC\AppFramework\Utility\SimpleContainer->resolve() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:142
 OC\AppFramework\Utility\SimpleContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/ServerContainer.php:171
 OC\ServerContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:97
 OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}() at n/a:n/a
 array_map() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:116
 OC\AppFramework\Utility\SimpleContainer->buildClass() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:124
 OC\AppFramework\Utility\SimpleContainer->resolve() at /snap/nextcloud/37046/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php:142
 OC\AppFramework\Utility\SimpleContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/ServerContainer.php:171
 OC\ServerContainer->query() at /snap/nextcloud/37046/htdocs/lib/private/Activity/Manager.php:245
 OC\Activity\Manager->getProviders() at /snap/nextcloud/37046/htdocs/apps/activity/lib/NotificationGenerator.php:94
 OCA\Activity\NotificationGenerator->populateEvent() at /snap/nextcloud/37046/htdocs/apps/activity/lib/NotificationGenerator.php:123
 OCA\Activity\NotificationGenerator->prepare() at /snap/nextcloud/37046/htdocs/lib/private/Notification/Manager.php:368
 OC\Notification\Manager->prepare() at /snap/nextcloud/37046/htdocs/apps/notifications/lib/Push.php:304
 OCA\Notifications\Push->pushToDevice() at /snap/nextcloud/37046/htdocs/apps/notifications/lib/App.php:58
 OCA\Notifications\App->notify() at /snap/nextcloud/37046/htdocs/lib/private/Notification/Manager.php:329
 OC\Notification\Manager->notify() at /snap/nextcloud/37046/htdocs/apps/activity/lib/NotificationGenerator.php:61
 OCA\Activity\NotificationGenerator->sendNotificationForEvent() at /snap/nextcloud/37046/htdocs/apps/activity/lib/Consumer.php:71
 OCA\Activity\Consumer->receive() at /snap/nextcloud/37046/htdocs/lib/private/Activity/Manager.php:157
 OC\Activity\Manager->publish() at /snap/nextcloud/37046/htdocs/apps/settings/lib/Listener/UserAddedToGroupActivityListener.php:92
 OCA\Settings\Listener\UserAddedToGroupActivityListener->handle() at /snap/nextcloud/37046/htdocs/lib/private/EventDispatcher/ServiceEventListener.php:86
 OC\EventDispatcher\ServiceEventListener->__invoke() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php:251
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php:73
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /snap/nextcloud/37046/htdocs/lib/private/EventDispatcher/EventDispatcher.php:94
 OC\EventDispatcher\EventDispatcher->dispatch() at /snap/nextcloud/37046/htdocs/lib/private/EventDispatcher/EventDispatcher.php:106
 OC\EventDispatcher\EventDispatcher->dispatchTyped() at /snap/nextcloud/37046/htdocs/lib/private/Server.php:527
 OC\Server->OC\{closure}() at n/a:n/a
 call_user_func_array() at /snap/nextcloud/37046/htdocs/lib/private/Hooks/EmitterTrait.php:105
 OC\Hooks\BasicEmitter->emit() at /snap/nextcloud/37046/htdocs/lib/private/Hooks/PublicEmitter.php:40
 OC\Hooks\PublicEmitter->emit() at /snap/nextcloud/37046/htdocs/lib/private/Group/Group.php:202
 OC\Group\Group->addUser() at /snap/nextcloud/37046/htdocs/core/Command/Group/AddUser.php:72
 OC\Core\Command\Group\AddUser->execute() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /snap/nextcloud/37046/htdocs/core/Command/Base.php:177
 OC\Core\Command\Base->run() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /snap/nextcloud/37046/htdocs/3rdparty/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /snap/nextcloud/37046/htdocs/lib/private/Console/Application.php:211
 OC\Console\Application->run() at /snap/nextcloud/37046/htdocs/console.php:100
 require_once() at /snap/nextcloud/37046/htdocs/occ:11
```

### Additional environment informations

- Ubuntu Server 22.04 LTS
- x86 (64 bit)
- Running in the Snap environment

### Configuration report

```shell
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dragoncloud.ddnss.de",
            "schedelcloud.ddnss.de",
            "localhost",
            "schedelcloud",
            "dragoncloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.2.1",
        "overwrite.cli.url": "https:\/\/dragoncloud.ddnss.de",
        "overwritehost": "dragoncloud.ddnss.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "admin_notifications",
            "occweb",
            "twofactor_gateway",
            "twofactor_admin",
            "nextbackup",
            "drop_account",
            "files_texteditor",
            "socialsharing_email",
            "socialsharing_facebook",
            "socialsharing_twitter",
            "whiteboard",
            "talk_matterbridge",
            "ocdownloader",
            "jsloader",
            "extract",
            "breezedark",
            "impersonate",
            "richdocumentscode_arm64",
            "music",
            "files_markdown",
            "login_notes",
            "files_downloadlimit",
            "twofactor_reminder"
        ],
        "loglevel": 2,
        "default_phone_region": "DE",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "token_auth_enforced": true,
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 180",
        "activity_expire_days": 365,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita"
        ],
        "theme": "",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - announcementcenter: 6.6.2
  - bookmarks: 13.1.1
  - breezedark: 26.0.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.0-beta.1
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - collectives: 2.7.0
  - comments: 1.17.0
  - contacts: 5.4.0-beta.1
  - contactsinteraction: 1.8.0
  - cookbook: 0.10.2
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0-beta.1
  - drop_account: 2.2.0
  - end_to_end_encryption: 1.13.1
  - external: 5.2.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_accesscontrol: 1.17.0
  - files_automatedtagging: 1.17.0
  - files_downloadlimit: 1.1.0
  - files_external: 1.19.0
  - files_markdown: 2.4.1
  - files_pdfviewer: 2.8.0
  - files_retention: 1.16.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - flow_notifications: 1.7.0
  - forms: 3.3.1
  - group_everyone: 0.1.13
  - impersonate: 1.14.0
  - integration_openai: 1.0.11
  - login_notes: 1.2.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.3.1
  - metadata: 0.19.0
  - music: 1.8.4
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - notify_push: 0.6.3
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - passwords: 2023.8.32-build5058
  - passwords_handbook: 2023.8.21
  - photos: 2.3.0
  - polls: 5.3.0-beta1
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quota_warning: 1.17.0
  - recommendations: 1.6.0
  - registration: 2.2.0
  - related_resources: 1.2.0
  - richdocuments: 8.1.1
  - richdocumentscode: 23.5.301
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.10.3
  - spreed: 17.1.0-rc.1
  - support: 1.10.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - tables: 0.5.1
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.14.0
  - twofactor_admin: 4.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_email: 2.7.3
  - twofactor_gateway: 0.20.0
  - twofactor_nextcloud_notification: 3.7.0
  - twofactor_reminder: 1.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
  - user_migration: 4.0.1
  - user_status: 1.7.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0 (installed 1.17.0)
  - encryption: 2.15.0 (installed 2.15.0)
  - snowflakestheme: 1.0.0 (installed 1.0.0)
  - survey_client: 1.15.0 (installed 1.15.0)
  - weather_status: 1.7.0 (installed 1.7.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional Information

- To simplyfy the error log, I executed the occ command for adding a user to a group with very verbose output. The log does not contains any other relvant entries, even on `debug` level.
- The app list has `polls` enabled. Keep in mind that when this is disabled, the is gone.
- The app list contains all apps I normaly have enabled. Keep in mind that I also tested this scenario with ALL apps disabled (except `acitivity` and `notifications`, of course).

**Comment by Pilzinsel64** [comment] 2023-09-02 10:51
Hm, looks like the error is gone in Beta 3. Just doesn't see any relevant changelog comment or commit message. 🤔 
If you confirm, just feel free to close this!

**Comment by dartcafe** [comment] 2023-09-02 15:25
>   Could not resolve OCP\Activity\IEvent! Class can not be instantiated

This error occured in the event system and was fixed in  https://github.com/nextcloud/polls/commit/8d2ac03f6c002fccafa7cdec30d0280a1cb2c690

I assume, that this was the cause in this issue as well.

I'll close here until further notice. Thanks for testing the beta anyways.

**Closed by dartcafe** 2023-09-02 15:25 UTC
Labels: bug
