### ISSUE TITLE
disallow multiple selection of poll options

### ISSUE THREAD

**Issue by janklostermann** [nextcloud/polls#905] opened 2020-04-19 10:47 UTC
**Problem**
The poll participant shall only be allowed to choose one of the various options (kind of radio button behaviour), to avoid inconsistent results for certain poll questions. 
Use case: How much confidence you have in our solution? (Options: none, little, much, full)

**Describe the solution you'd like**
If the poll participant already selected one item and now selects another, the formerly selected one shall be un-selected. Therefore at any time there is at most 1 poll option selected (none, little, much **or** full from the example).

This could be configurable in the "Configuration" section under "Poll configurations", e.g. "allow multiple selections" which is selected by default, but can be actively deselected by the poll creator. (Thus the current behaviour would not change and the configuration is well understandable.

**Describe alternatives you've considered**
The only alternative I see is asking the participants for friendly and non-errorneous behaviour, which could create problems in bigger polls, as you always have to check and, in case, correct the result manually.

**Comment by dartcafe** [comment] 2020-04-19 20:29
Duplicate of #738

**Closed by dartcafe** 2020-04-19 20:29 UTC
Labels: duplicate
