### ISSUE TITLE
Add pictures to poll options

### ISSUE THREAD

**Issue by makayabou** [nextcloud/polls#517] opened 2019-02-12 00:34 UTC
We already can create a poll by date or text item.
I would like to be able to create polls by image.
For example: wich draw should we choose as main character for our game?
Picture 1 or 2 or 3...
Thank you!

**Comment by dartcafe** [comment] 2019-02-14 11:39
@makayabou I had this on my mind too. But an issue for the backlog.

**Comment by CATER-COM** [comment] 2020-04-17 18:31
+1

**Comment by zer0brain** [comment] 2020-04-21 18:45
+1

**Comment by dartcafe** [comment] 2021-08-21 17:40
closing as duplicate of #940

**Closed by dartcafe** 2021-08-21 17:40 UTC
Labels: enhancement
