### ISSUE TITLE
continuous reload for public links

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/polls#96] opened 2016-10-27 08:54 UTC
Polls Version: 0.7.2.1
NC Version: 10.0.1

Continuous reload does occur if polls will be accessed by public link without logon/user account.

Browser: **Chrome 54.0.2840.71**
![2016-10-27-polls-reload-error_chrome](https://cloud.githubusercontent.com/assets/21206978/19760812/a7dce736-9c33-11e6-98e6-1d1ebef57899.jpg)

Browser: **MS Edge**
![2016-10-27-polls-reload-error_edge](https://cloud.githubusercontent.com/assets/21206978/19760813/a7dd8bd2-9c33-11e6-9e71-dbef55b09244.jpg)

Browser: **MS IE11**
![2016-10-27-polls-reload-error_ie11](https://cloud.githubusercontent.com/assets/21206978/19760811/a7db579a-9c33-11e6-9ea6-74b9020b0035.jpg)

**Comment by v1r0x** [comment] 2016-10-27 10:37
I'll have a look at it this weekend. Are your screenshots from different browsers? Does this occur on all browsers? Or is there anything in the screenshots I missed? :smile:

**Comment by nextgen-networks** [comment] 2016-10-27 11:10
@v1r0x have updated original post with information about the different browser engines.

Thanks for your support!

**Comment by v1r0x** [comment] 2016-10-27 11:42
Does this only happen in IE11? Or in Edge/Chrome as well?

**Comment by nextgen-networks** [comment] 2016-10-27 12:48
:-) it does happen on all the Browser Versions mentioned above.
I tried several other client computer in the same and in remote/other networks and all behave the same way.

The error message in the top is an indicator for the continuous reload problem.
-> translated: "Problem while loading the website. Website will be reloaded in 5 seconds."

**Comment by v1r0x** [comment] 2016-10-27 12:53
I'm from germany, but thanks :wink: 
I thought you refer to the "Waiting for" in IE11.

Is there anything in the oc/nc logfile? And does it happen for all (e.g. new) public polls?

**Comment by nextgen-networks** [comment] 2016-10-27 20:56
... ok - there has no log entry created while doing the following actions:
- delete old poll
- setup new poll (public)
- open public poll as anonymous/not logged in user and faced the reload problem

As there does not exist any "old" poll i've no possibility to check this scenario.

Thanks for your investigation!

**Comment by v1r0x** [comment] 2016-10-27 23:15
Did you check `owncloud.log` and `nextcloud.log` (If you've switched from oc to nc)?

I tested it with firefox and had no problems. I'll do some tests with chrome/ie and maybe there is something wrong...:)

**Comment by nextgen-networks** [comment] 2016-10-28 09:25
Only the nextcloud.log does exist and by now only with three share/dav relevant entries and four more from Rainloop webmail - so no issues documented by the polls plugin.

**Comment by v1r0x** [comment] 2016-10-28 09:48
This is very weird. Is there anything in the browser's javascript console?

**Comment by nextgen-networks** [comment] 2016-11-03 13:56
@v1r0x:
Sorry for the delay - here is what chromes console told me:

![2016-11-03_polls_continuous_reload_console-output](https://cloud.githubusercontent.com/assets/21206978/19968566/6d641942-a1d5-11e6-988b-561b72448447.jpg)

**Comment by v1r0x** [comment] 2016-11-03 14:05
Does this only happen in the polls app? Because the error in the console is caused by the apporder app, but maybe this error is unrelated to the reload error.

**Comment by nextgen-networks** [comment] 2016-11-03 14:15
YOU ARE MY MAN! Thanks for the the sharp view to the log!
It's definitely related to app order and i think it's caused by it.

Workaround:
deactivate AppOrder

Possible solution:
Allow non authenticated users the access to AppOrder to avoid reload.

**Comment by v1r0x** [comment] 2016-11-03 14:19
Glad it works now :)

Best would be to open an issue at the apporder repo. Don't know if there is something I could do about it.

**Comment by nextgen-networks** [comment] 2016-11-03 14:22
... jipp - typing the latest infos to an new ticket already ;-)

Thanks for your time and patience!

... and for your app!!!

**Comment by juliushaertl** [comment] 2016-11-06 13:04
@v1r0x I think this should be fixed in the polls app, as other public pages (like in the gallery app) do not produce this error.

From https://github.com/juliushaertl/apporder/issues/24 
> I just had a quick look, but it looks like the TemplateResponse constructor in your controller needs an additional parameter ($renderAs='guest') for public pages. I'm sorry I cannot test that right now, but I'll do so if i find some time.

The current public page of the polls app also shows elements like the user menu on the left, which should not be visible for non logged in users.

**Comment by v1r0x** [comment] 2016-11-06 21:33
Thanks for your reply and your suggestion. Will test your solution. Thanks!

**Comment by nextgen-networks** [comment] 2016-11-15 09:24
reopen based on feedback of @juliushaertl

**Comment by v1r0x** [comment] 2016-11-16 01:10
@juliushaertl I added `'guest'` as parameter after the parameter array `return new TemplateResponse('polls', 'goto.tmpl', [], 'guest');` but the result looks really weird.
![guest-poll](https://cloud.githubusercontent.com/assets/9248714/20330808/a1d54a9a-aba1-11e6-8de8-92471f8ce5c6.png)
Any idea what's wrong?

**Comment by juliushaertl** [comment] 2016-11-16 18:53
@v1r0x Ok, it should be 'base' not 'guest', sorry for the wrong information.

After testing, i saw that this will render the public pages, but will not show the top bar with logo.
Other apps with public pages, like the gallery app or even the shipped files_sharing for example add a custom template with the header bar.

https://github.com/nextcloud/gallery/blob/master/templates/public.php#L49-L69
https://github.com/nextcloud/server/blob/master/apps/files_sharing/templates/public.php#L37-L73

**Comment by dartcafe** [comment] 2017-09-18 05:02
@v1r0x Is that issue still an issue?

**Comment by v1r0x** [comment] 2017-09-18 08:14
I don't know, but I think yes. Haven't decided yet which template for not logged-in users is the best. Looks like every other app has another template...

**Comment by dartcafe** [comment] 2017-09-18 10:44
As far as I saw, the public pages are ok, besides the fact, that there are navigation elements, which don‘t work, because the user is not logged in. I just find the topic of the issue is a little bit confusing.

**Comment by dartcafe** [comment] 2017-10-13 09:22
@nextgen-networks @v1r0x: This Issues still points to the 0.7.4 milestone. I cannot reproduce this. Is this bug still present or could we close the PR?

**Comment by jochen1205** [comment] 2017-11-12 12:52
Unfortunately bug is still present. Owncloud 10.0.3
Checked on several browsers on mobile and Desktop: Firefox, Safari, Chrome

**Comment by muhackl** [comment] 2017-12-07 07:21
Same issue here. Owncloud 10.0.3; Polls 0.8.0.
Safari, Chrome (Mac)
Chrome output:
![screen](https://user-images.githubusercontent.com/3956731/33703224-88b7d152-db27-11e7-8f3f-c3015c718ea5.png)

**Comment by splitt3r** [comment] 2017-12-07 09:00
Does this happen in any other app? Is there anything special about this poll / the user the avatar fails to load for? Could you create an public poll to show us the issue / an account?

**Comment by muhackl** [comment] 2017-12-07 12:11
This happens just in the polls app.
And it just appears, if I set the poll public or hidden. 
But it does not depend, if user names are anonymous or not. 
As soon as I am logged in and open the poll, the error does not occur.
Any clues?

**Comment by dartcafe** [comment] 2017-12-07 21:12
There seems to be some incopatibility with the avatarmanager, when the avatars are loaded via JS in public polls. I can reproduce this as well. 

But I cannot see a relationship to the starting issue. Seesms to be a nother issue or do I understand something wrong?

**Comment by dartcafe** [comment] 2017-12-07 21:13
And BTW: I still cannot reproduce the starting issue.

**Comment by muhackl** [comment] 2017-12-08 14:00
What exactly do you mean by „the starting issue“? 
Any idea how to solve or workaroud this issue?

**Comment by dartcafe** [comment] 2017-12-08 15:39
This issue started with something around a continuous loading of the page in public polls (see screenshots). Something I cannot reproduce. 

The last comments regard an issue related to not loading avatars and which I can reproduce. I cannot see a relationship between both things. 

And no, I have no workaround for that at the moment. I will investigate next week. Maybe someone else can solve that faster or better.

**Comment by muhackl** [comment] 2017-12-08 15:46
Well the relation is (but unfortunately I did not state this clearly): I get exactly the same error message and the same symptom as mentioned in the starting post: page reloads every 5 seconds (as announced in the error message).

**Comment by splitt3r** [comment] 2017-12-08 16:14
Had a quick look and seems to be just another Nc vs. oC thing. Nc avatars are public https://github.com/nextcloud/server/blob/master/core/Controller/AvatarController.php#L115-L118 but oCs aren´t https://github.com/owncloud/core/blob/master/core/Controller/AvatarController.php#L107-L108.

**Comment by dartcafe** [comment] 2017-12-11 06:08
@muhackl Please try #266

**Comment by dartcafe** [comment] 2017-12-11 06:09
Test instance: https://oc10.yagst.de/index.php/apps/polls/poll/12rdzh9QYiFZaFz4

**Comment by muhackl** [comment] 2017-12-14 06:02
I changed the code of vote.js. After that, the 5-second-reload issue was no longer there. But there are no Dates shown any longer. Just zeros (0). 
Another symptom I was watching already before this fix: When adding a new poll, I just chose several dates and just one time so I get one column. After one anonymous took part on the poll and I get back as admin to the edit mode of the poll, it looks like that (see attachment). There is something terribly wrong I think.
![bildschirmfoto 2017-12-14 um 06 59 01](https://user-images.githubusercontent.com/3956731/33977758-bc60ab76-e09c-11e7-8dbb-e663ba0ccff5.png)

**Comment by dartcafe** [comment] 2017-12-14 07:13
There are several changes since the 0.8.0. So better pull the 0.8.1 branch to test. Just updating a single file will have side effects. If the continuous erload will no more occur, I would prefer to close this littel issue with this huge amount of comments 😬

**Comment by muhackl** [comment] 2017-12-14 08:47
Polls 0.8.1 fixed all issues for me.
- 5-seconds-reload
- Self-muliiplying rows
Regarding me, issue can be closed.
Thanks a lot!

**Comment by dartcafe** [comment] 2017-12-14 10:08
👍 Great! Thanks.

**Closed by dartcafe** 2017-12-14 10:08 UTC
Labels: bug

**Comment by Byter3** [comment] 2019-03-04 23:03
Hi there!

I'm having this issue as well!

Any idea what is still wrong?
I'm running oc version 10.0.10.4
Poll version: 0.8.1

**Comment by dartcafe** [comment] 2019-03-06 06:58
Try the 0.8.3 Release. As mentioned in the readme, we dropped support for ownCloud. Sorry for that.
