### ISSUE TITLE
Link in mail, empty site

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/polls#945] opened 2020-05-29 05:11 UTC
Hello,

I got a mail from polls about new activity with a link "go to the poll". If I click the link, I got a empty site:

![image](https://user-images.githubusercontent.com/1249295/83223629-a173ed80-a17b-11ea-9f5a-ec1eff605103.png)

The link in the mail is:

https://example.org/cloud/index.php/apps/polls/vote/30

If I click "my polls" I see the right poll. And if I click the poll with the new activity, I have the same URL.

Nextcloud Version 18.0.4 on Debian 10 with Apache2 and MariaDB. Polls have version 1.4.3.

Any ideas?

**Comment by dartcafe** [comment] 2020-05-31 07:25
¯\_(ツ)_/¯ Tested on different instances. No issue. I can open the poll from the mail as well from the navigatoin without problems.

**Comment by Benance** [comment] 2020-06-23 05:54
Hello
I've nearly the same problem with links in email notifications.
The link is not good.
It's https://mydomain.tld/index.php/apps/polls/vote/a_number
It would be https://mydomain.tld/cloud/index/php/apps/polls/vote/a_number
be cause my nextcloud instance is hosted at https://mydomain.tld/cloud

**Comment by dartcafe** [comment] 2020-06-23 09:40
OK. Now I see. Your installation is inside a subfolder. I will check this.

**Comment by brtptrs** [comment] 2020-07-28 21:34
Hello,
we are seeing a similar error. 

Activity mails contain links that don't work and load an empty page:
https://cloud.example.com/files/index.php/apps/polls/vote/4811

When /index.php is removed from the url the page loads normally
https://cloud.example.com/files/apps/polls/vote/4811

Our NC instance is in a "files" sub-directory.

**Comment by dartcafe** [comment] 2020-09-14 18:55
So. I testet with the current dev-version (polls 1.5) with an NC20 installation in a subfolder. All links are correct. I can't reproduce with this combination. As the links are generated with the core functions I have limited possibilities to get further in this. 

The same result on an instance running NC19 with 1.4.3 installed from appstore. Based on the provided information I cannot resolve this issue. Sorry. Any more Information about your installation or a testaccount could help to investigate. 

Do you have any rewrite rules added to the .htaccess or another custom configuration?

**Comment by brtptrs** [comment] 2020-09-18 07:23
Yes, 1.5 seems to work.
I've just tried it on:
NC19
Version = "Different default view" (RC2?)

**Comment by dartcafe** [comment] 2020-09-18 13:26
Strange. I cant't remember, that we changed something here. But while testing I fixed some icon links, which were relatively hardcoded. 

> Version = "Different default view" (RC2?)

yes RC2 with some missing translations and with the possibility to define the default view for date and text polls via the user settings.

I think, this gonna be the next RC and hopefully the release.

**Comment by dartcafe** [comment] 2020-09-21 11:05
I cannot actually reproduce this. I will leave this open until further notice. 
@BurtGummer @Benance @brtptrs I released the final RC3. If you could test this, please leave some feedback here or wait for the release (will come before NC20). Anyway: Feedback would help...

**Comment by Benance** [comment] 2020-09-24 21:01
All right. I will upgrade my nextcloud instance from 18 to 19 tomorrow and I will give you a feedback. 
Thanks for your work 
Have a good night.

**Comment by brtptrs** [comment] 2020-09-28 10:43
On our live system with NC19 and polss 1.5 I am still seeing this problem. 
On our testing sever not. I will have a closer look to try and find the difference between the two installations. On both NC 19 is installed in a sub folder. That does not seem to be the problem.

**Comment by DBJRdev** [comment] 2020-10-05 10:32
With the most recent Nextcloud 19.0.3, Polls 1.4.3 from the AppStore I can replicate the issue on a Hetzner Managed Server and a All-Inkl shared hosting:

1. Nextcloud is configured to omit the index.php in the URL. (via 'htaccess.RewriteBase' => '/', in config and occ)
2. System emails with the subject "Umfragen App - Neue Aktivität" (Polls app - new activity) have a button "Zur Umfrage gehen" (go to poll), which contains the index.php -> and leads to a blank page.
3. When you take out the index.php in the link manually, the correct poll appears.

**Comment by brtptrs** [comment] 2020-10-05 13:08
As @DBJRdev mentioned the problem in 1.4.x might have something to do with 'htaccess.RewriteBase' since we also have this entry in the aur config.php

**Comment by dartcafe** [comment] 2020-10-05 21:21
@DBJRdev 
Reproduction (NC 19.0.3, Polls 1.4.3): 
* Added 'htaccess.RewriteBase' => '/' to the config
* called /occ maintenance:update:htaccess

✔️ All shares generated after this change link to https://nextcloud.com/apps/polls/s/Ou9iz6tN9xJFTE13 instead of https://nextcloud.com/**index.php**/apps/polls/s/Ou9iz6tN9xJFTE13 (including link in invitation mail)

Of course, an invitation mail generated before the change, still links to https://nextcloud.com/**index.php**/apps/polls/s/Ou9iz6tN9xJFTE13

This route is no more identified by the app, because we get our base route from the server, and this is then https://nextcloud.com and no more https://nextcloud.com/index.php

I guess there must be added some rewrite rule on the server side to rewrite /index.php/... to /...

**Comment by tessus** [comment] 2020-10-26 15:03
I was asked to report my issue here:

The email notification (subject: Polls App - New Activity) includes a link that does not work:

`https://****/index.php/apps/polls/vote/13`

When I remove `index.php` all is good: `https://****/apps/polls/vote/13`

**Comment by dartcafe** [comment] 2020-10-26 19:08
As i wrote above. I cannot reproduce this behavior. Links are correct here. 
Sure, you followed the following steps? 
* Added 'htaccess.RewriteBase' => '/' to the config
* called /occ maintenance:update:htaccess

**Comment by tessus** [comment] 2020-10-26 19:12
Yes, I did.

**Comment by dartcafe** [comment] 2020-10-26 19:16
Strange. I can switch back and fore and the links are all correct. Tested with 1.4, 1.5 and 1.6 on different sites and NC versions.

**Comment by tessus** [comment] 2020-10-26 19:26
I just looked at the `.htaccess` file and I think there's a logical error in there.

```
<IfModule mod_php7.c>
  php_value mbstring.func_overload 0
  php_value default_charset 'UTF-8'
  php_value output_buffering 0
  <IfModule mod_env.c>
    SetEnv htaccessWorking true
  </IfModule>
</IfModule>
```

This env var won't be set in case one is using php-fpm. So, if your code actually checks for `htaccessWorking`, it won't work.

**Comment by dartcafe** [comment] 2020-10-26 19:32
Nothing, what we do in polls. Polls doesn't care about any config files or other files in the NC installation.

**Comment by tessus** [comment] 2020-10-26 19:48
If that were the case, there wouldn't be a requirement to run `occ maintenance:update:htaccess`.

Anyway, can you point me to the code where the notificatiob link is built. Something is off. I'm using Nextcloud 18.0.10, but @DBJRdev also had the issue on 19.x

**Comment by dartcafe** [comment] 2020-10-26 21:12
https://github.com/nextcloud/polls/blob/e5fceacbed49278c0ce4f11c7bf846a73e6e7f8e/lib/Service/MailService.php#L192-L200

**Comment by tessus** [comment] 2020-10-26 21:38
For some reason `linkToRouteAbsolute` returns the wrong URL.

**Comment by tessus** [comment] 2020-10-26 21:58
I don't know how to fix this. Everything else works. The links that are generated in the polls app are without the `index.php`, so the app creates correct links. However, the notification email contains the wrong link.

**Comment by dartcafe** [comment] 2020-10-27 07:47
Does the invitation email contain correkt links? Or are they wrong as in the notification mail?

**Comment by dartcafe** [comment] 2020-10-27 07:51
Also see to the information in https://docs.nextcloud.com/server/18/admin_manual/configuration_server/config_sample_php_parameters.html (htaccess.RewriteBase)

> After setting this value run occ maintenance:update:htaccess. Now, when the following conditions are met Nextcloud URLs won’t contain index.php:
>
>    mod_rewrite is installed
>    mod_env is installed

**Comment by tessus** [comment] 2020-10-27 17:52
Thanks for the info, but I use `mod_rewrite` and `mod_env` constantly. I can show you redirect rules with regex that fill a page.

Either way, this is not a rewrite issue. I configured it according to the docs, so it can't be a misconfiguration. If it was, I would have the index.php in my other links and when I browse on my nextcloud instance. I don't.

Once again. The only place where I see an `index.php` is in the email that gets sent from the polls app.

> Does the invitation email contain correkt links?

Yes.

The links are correct for "internal" invitation links (for nextcloud users) and "external" invitation links (for people that do not have an account).

**Comment by tessus** [comment] 2020-10-27 21:54
Here's some additional info that should help narrow this down.

A notification email (with the subject: `Polls App - New Activity`) sends out the same link to me (creator) and people with no account (external/public users). While their invitation email has a proper link with their personal access link, the update notification emails do not have it.

So there is a problem with update (send on activity) emails.

While I could theoretically remove the `index.php` manually to get to the poll, public users cannot, since they don't have an account. All activity emails have a link in this format: `https://**server**/index.php/apps/polls/vote/NN`

**Comment by dartcafe** [comment] 2020-10-27 21:59
The notification mails are sent out via background job. Then the cli configuration seems to have some problem. Maybe #891 can give some hints. That was a similar problem.

**Comment by tessus** [comment] 2020-10-27 22:06
Mine is set to `https://**server**` and definitely not `https://**server**/index.php`

But even if that was the issue, it wouldn't fix the problem that external users get an internal link.

**Comment by dartcafe** [comment] 2020-10-27 22:33
I am confused. What are we talking about in this issue? 
This issue is about links, which include index.php and they shouldn't. As the base URL is generated from the servers core functions, there is nothing more I can do here. It must be a configuration issue or a bug in the server. Maybe the devs in the server repo can help. 

@nickvergessen Any idea, what could be the reason here? 

@tessus If there is another problem with wrong links (external user get an internal link), please open another issue and provide some information, how I can reproduce this issue. Otherwise it is hard to track the issues.

**Comment by tessus** [comment] 2020-10-27 23:20
We are talking about a wrong link that is sent. (Links in invitation emails are correct.) The problem occurs for `Polls App - New Activity` emails.  
But during my tests I found out that there are actually 2 issues:

1. The link includes a `index.php`, which results in an empty page upon clicking on it, even though the config is correct and all other emails that are sent by Nextcloud (or are presented within the UI) are without the index.php
2. Emails that are sent to a poll user, who does not have a Nextcloud account, contain a link `https://**server**/index.php/apps/polls/vote/NN` which won't work for them, because they can only access the poll via their personalized link, which is correctly sent in their invitation email

So maybe the second issue requires a separate ticket. But the first one is exactly the problem the OP described.

**Comment by nickvergessen** [comment] 2020-10-28 08:21
I think https://github.com/nextcloud/polls/commit/79464f9a584c7546b8a1b2b310f37010e3927414 might help to solve it, did this already get released and everyone updated to it?

**Comment by nickvergessen** [comment] 2020-10-28 08:22
Other than that I have no further clue and more expect this to be a config issue rather than a bug in your app (at least looking at the links you create in lib/Service/MailService.php )

**Comment by dartcafe** [comment] 2020-10-28 14:10
> I think [79464f9](https://github.com/nextcloud/polls/commit/79464f9a584c7546b8a1b2b310f37010e3927414) might help to solve it, did this already get released and everyone updated to it?

It worked before and in the end `linkToRouteAbsolute` does exacly what the substituted routine did, judging from the server source code. 

And no, it not yet released. RC is comming this week.

**Comment by dartcafe** [comment] 2020-10-28 19:07
> Other than that I have no further clue and more expect this to be a config issue rather than a bug in your app (at least looking at the links you create in lib/Service/MailService.php )

Thanks. I hoped, you have an idea, because I do not now the server. But I agree, i guess it is a configuration issue. I will close this, because we cannot fix this in polls. Feel free to reopen, if there are new informations and we can do anything here.

**Closed by dartcafe** 2020-10-28 19:07 UTC
Labels: awaiting feedback, investigate

**Comment by tessus** [comment] 2020-10-28 19:28
It's not a configration error, unless the documentation is wrong or you gave me the wrong info.

My setup is exactly what you told me it should be, so how can it be a configuration error?

**Comment by Benance** [comment] 2021-02-09 08:52
Sorry for the comment on a closed issue, but even after upgrading polls app to 1.7.5, I still have the problem of wrong URL in notifications email.
the URL is good in invitation email for external users (https://mydomain.tld/cloud/apps/polls/s/mteS0zvk9bH4H6qh for example) but not in notifications ones (https://mydomain.tld/index.php/apps/polls/vote/9). It would be https://mydomain.tld/index.php/cloud/apps/polls/vote/9 instead because my nextcloud instance is installed on a subfolder "cloud".
Thanks for your support

**Comment by dartcafe** [comment] 2021-02-09 21:38
Check the CLI settings in your config.php. See here: https://github.com/nextcloud/polls/issues/1342#issuecomment-759514562

**Comment by Benance** [comment] 2021-02-10 08:09
Hello @dartcafe 
I've checked the line in my config.php, and it's already right:
'overwrite.cli.url' => 'https://mydomain.tld',
any other idea?
Thanks

**Comment by dartcafe** [comment] 2021-02-10 13:07
I recomment read the administration docs on docs.nextcloud.com or you try to find or ask for solution on help.nextcloud.com, because this is an configuration issue of your instance and not polls related.

**Comment by Benance** [comment] 2021-02-10 14:45
all right
According to the doc, I've changed 
'overwrite.cli.url' => 'https://mydomain.tld', 
with
'overwrite.cli.url' => 'https://mydomain.tld/cloud',
now the link in the notification email is ok.
Thanks fot the tip
