### ISSUE TITLE
Can't save a TXT poll: "Click on cells to turn them green"

### ISSUE THREAD

**Issue by pmd2016** [nextcloud/polls#131] opened 2017-07-18 13:06 UTC
If I try to add a public text poll, I get the following message:

> Nothing selected!
> Click on cells to turn them green

<img width="990" alt="screen_shot_2017-07-18_at_14_59_54" src="https://user-images.githubusercontent.com/19425130/28318279-760d957c-6bca-11e7-9cff-12433aef4802.png">

**Comment by joergmschulz** [comment] 2017-07-18 13:15
The alert exactly tells you what to do: In order to activate the selections you have to click on the red cells containing the X. Then it will work.

**Comment by pmd2016** [comment] 2017-07-18 13:21
Ah. I see. It's not that obvious what you need to do IMHO... 😉

**Comment by v1r0x** [comment] 2017-07-18 17:10
Can we close this or should there be a description or anything in the UI so it's clear what to do?

**Comment by q00d0** [comment] 2017-07-18 20:24
I had the same "problem". A description would be nice!

**Comment by v1r0x** [comment] 2017-07-18 22:48
Ok, as you wish 😉 Any suggestions?

**Comment by pmd2016** [comment] 2017-07-19 07:32
The way I interpret the 'insert text' screen is as answer options to the poll. It is not very clear that you have to answer the poll yourself before you can save the poll. It would be great if you can just setup a poll and let others answer without the need to answer the question yourself first. Does that make sense?

**Comment by v1r0x** [comment] 2017-07-19 07:43
You don't have to answer the questions, it's just about selecting the available questions you want in your poll. Only entries with a green checkmark will be in the poll.

**Comment by q00d0** [comment] 2017-07-19 07:50
Maybe radio buttons fix this - "active" and "inactive" or something like this.

**Comment by DJCrashdummy** [comment] 2017-07-20 05:52
IMHO this problem only occurs, if you haven't already created a date-poll with this app, so...

- a little bit more clear statement like in https://github.com/v1r0x/polls/issues/131#issuecomment-316059909 would definitely be fine.

- also activating the lines by default could be a solution.
if you've done a mistake, you start thinking about "how can i get rid of it" anyway. - and if you've already created a date-poll, the solution will be pretty obvious (with the same UI).

- if you really want to change the UI, maybe something like a trashcan for deactivating/deleting would make it more clear.

- or better, similar to https://github.com/v1r0x/polls/issues/131#issuecomment-316302033, the important thing is to have both options available to be more self-explaining _(if people have/see only one option, they usually don't think about it or any function behind it.)_:
wether it is the "X" and the "check mark" side by side and the selected gets colored, both with radio buttons or radio buttons with text is secondary.

**Comment by pirate** [comment] 2017-09-10 04:27
What does the red X even do?  What's the purpose of putting in poll options that are X'ed out?

**Comment by dartcafe** [comment] 2017-09-13 12:49
It is the default behavior. The red x signals: this option is not offered to the participants. 
If you klick on it, it turns to a green check sign and the option will be added to the poll. 
Not really intuitive and what a user expects. I think this is gonna be under investigation.

**Comment by dartcafe** [comment] 2017-09-13 17:34
Closing this because of #160

**Comment by DJCrashdummy** [comment] 2017-09-13 18:49
@dartcafe i'm not sure if it is a good idea to close an issue with a longer message queue and collected ideas instead of the freshly created duplicate (although it is not an exact duplicate).

**Comment by dartcafe** [comment] 2017-09-13 20:16
Apologizes. Thought it was easier to start with the fresh one. Didn't want to bother someone. Maybe my fingers have been too fast...

**Comment by AceSlash** [comment] 2017-09-15 16:11
I too, don't understand this option.

When I take the time to add an item, it should be immediately available to the poll. The only option should be to remove it (or eventually change the order of option, which is not possible now).

What's the point of creating an option and then don't use it? I don't get it.

**Comment by joergmschulz** [comment] 2017-09-15 18:48
when you start creating complex polls with multiple dates and multiple hours, you'll see why a default-X has been a good idea.
As this seems to be the minority of polls, I would like to back the proposition to always add new options as green even when multiple hours are given.

**Comment by DJCrashdummy** [comment] 2017-09-15 19:11
@dartcafe np, no harm done! :wink: 

@AceSlash yes... the handling, especially of text-polls, is not ideal for know. already suggested some possible solutions https://github.com/nextcloud/polls/issues/131#issuecomment-316604006, where the second and fourth point are my favorites, but somehow also all 4 solutions together can be applied.
and btw @dartcafe is doing an awesome big redesign at the moment! - but i have no idea for now, if this is also addressed in some way...

**Comment by DJCrashdummy** [comment] 2017-09-15 19:21
@joergmschulz this issue is (mainly) about text-polls, and in this case i'm also definitely for activating new options by default. for date-polls it is debatable IMHO... but it seems to also be an issue there #160.

**Comment by v1r0x** [comment] 2017-09-15 19:26
I think the red 'x' signalizes deleting the option. Maybe a '?' instead of the x and no background. Additionally a heading or desc would be useful.
I'd prefer the current (opt-in) solution, but re-think the UI/UX.

**Comment by dartcafe** [comment] 2017-09-16 06:03
At least this way of creating the polls will be a problem on mobile devices. Maybe, we should redesign it as well.

**Comment by DJCrashdummy** [comment] 2017-09-16 10:39
i think the best solution (without a big redesign of the UI) for text-polls(!) would be activating new options by default and have both statuses visible all the time, since it doesn't need that much space.
and that can be designed with radio buttons and the 2 existing icons or just the 2 icons and the not applied one is kind of grayed out.

**Comment by dartcafe** [comment] 2017-12-14 05:32
Will be fixed when recreating the edit/create page.

**Comment by WNYmathGuy** [comment] 2018-03-07 16:47
Sorry to weigh in on this, but I got here because of the error message. I was thinking about deactivating the Polls app assuming it didn't work, but I decided to search the error instead.

Now I'm no degree carrying interface psychologist, but "Affordances" for my particular mind would dictate that after I added items, that they were _added_. Therefore the red "**X**" icon was to remove them. Why would I need to approve of something I already _added_? It's like putting a push plate on a door that you pull to open.

The error message was too generic for me to know what it meant. `Nothing selected! Click on cells to turn them green.` should be `No options confirmed yet. Click red X icons to confirm items you added.`.

**Comment by torantal** [comment] 2018-03-11 21:06
Also came her because I though it didn't work. Looking forward to a default of adding items.

**Comment by dartcafe** [comment] 2018-04-29 07:13
I completely changed the create page, so that the default date picker of nextcloud is used and new poll options are simply added to a list of options.
![grafik](https://user-images.githubusercontent.com/26707476/39404151-24422e44-4b8d-11e8-88c5-975b52334364.png)

![grafik](https://user-images.githubusercontent.com/26707476/39404153-36e866bc-4b8d-11e8-8e50-fc582eee224d.png)
So there is no more matrix with time and date selections and options can be removed with a single click on the trash bin icon.

**Comment by DJCrashdummy** [comment] 2018-04-29 08:09
well... for a date-poll (after getting used to it) i liked the martrix because it provides a kind of an easy overview, but this issue is about text-polls and for them this looks like a huge improvement! :+1: 

not to mention using the default date-picker of NC is also a big improvement regarding design and UX.
btw: is the dates-list sorted by date & time or just one after another when added? - and is the same sorting also shown to participants and not just for creating/editing?

additional: are also text-poll options shown one after another or sorted alphabetically (which will make much less sense than sorting by date&time for date-polls)...?
instead at least for text-polls a possibility to manual sort the options may be the icing on the cake.

**Comment by dartcafe** [comment] 2018-04-30 06:01
Dates are ordered by date and time and of course the presentation to the user is ordered too. Same as the current behavior.
![pollsadddates0 9](https://user-images.githubusercontent.com/26707476/39416336-74851456-4c4c-11e8-855a-c41bef6705d6.gif)

The matrix has the disadvantadge, that date polls without time or with a time range are not possible. 
The text list is just by ordered by adding time. The last added option is put on the last position. Perhaps, we can make it orderable by drag and drop. But not at the moment.

**Comment by DJCrashdummy** [comment] 2018-04-30 06:33
@dartcafe well... because i mentioned one interesting feature of the matrix it doesn't mean it has no disadvantages. :wink: 
to make it clear: i'm completely fine with this for date- & text-polls... over all it is definitely an improvement! :clap: and as already mentioned, the manual sorting would just be the icing on the cake, since you can already achieve the same result with a little bit more thinking (except for date-polls... but i'm not sure if manual sorting there makes sense anyway).

**Comment by dartcafe** [comment] 2018-04-30 12:36
Sorting could be a helpful feature, if the order of the options is essential for the creator. But this will not be done in this PR. I am done with the refactoring. Now UX and some improvemnts are coming up. I want to finish the first step of recreating the edit/create page and merge this PR.

**Comment by dartcafe** [comment] 2018-06-18 05:30
Selecting dates and text options was changed. No more red crosses and green checkmarks...

**Closed by dartcafe** 2018-06-18 05:30 UTC
Labels: 3. to review, enhancement

**Comment by natrius** [comment] 2018-07-10 12:03
I am looking forward for the update, i found this one while wondering what that ominous "green field" should be. The red cross does obviously (for me) mean: Delete this option. 
Thanks for keep working on that one!

**Comment by valkalon** [comment] 2018-09-05 14:51
Joining Natrius, on the update wait! You're software is just so great for shared planning, a must have for us! Thanks!

**Comment by AndyLicht** [comment] 2018-10-11 06:09
Hi, i want to use polls with nextcloud 14.0.1, but nothing works really. So i have to set a green raw for date options, but i can not set it.

**Comment by natrius** [comment] 2018-10-11 09:37
@dartcafe @DJCrashdummy 
Any idea when 0.9 will be available in the Nextcloud app store?

**Comment by torantal** [comment] 2018-12-10 02:59
> I completely changed the create page, so that the default date picker of nextcloud is used and new poll options are simply added to a list of options.
> So there is no more matrix with time and date selections and options can be removed with a single click on the trash bin icon.

Sorry if this is somehow obvious, but which version is this displayed design now in? I'm running 0.8.3 and it's still the old behavioiur.

**Comment by natrius** [comment] 2018-12-10 11:54
Seems like it is in version 0.9 and according to https://github.com/nextcloud/polls/releases/ you can install 0.9 manually and try it. But it should not be to far away, as there is 0.9.1RC2 already there. 

Someone has a short explanation how to install it, in case i want to try?

**Comment by natrius** [comment] 2018-12-10 14:33
Oh, sweet. Thanks for the explanation and in that case i will just wait for the new version. Don't worry, can happen. :)
