### ISSUE TITLE
Allow participants to add options

### ISSUE THREAD

**Issue by errnesto** [nextcloud/polls#1127] opened 2020-09-30 11:18 UTC
**Is your feature request related to a problem? Please describe.**
We have polls where multiple users are adding suggestions. It is a little anoying that they have to send it to the creator
and then wait untill they enter a new option. So we can't colaborate on creating a poll

**Describe the solution you'd like**
It would be nice if there was an option to allow participants to add new options to a poll.

**Describe alternatives you've considered**
Also a option "can edit" to let users - also users with a share link - edit the poll (like admins) or #1095 would work nice for my specific this use case.

**Comment by dartcafe** [comment] 2020-10-02 12:21
Related to #1094

**Comment by Tie-fighter** [comment] 2020-10-15 12:33
This would be highly appreciated!

**Comment by dreamflasher** [comment] 2020-11-18 07:56
Duplicate of https://github.com/nextcloud/polls/issues/496 – unclear why #496 got closed.

**Comment by dartcafe** [comment] 2020-11-18 09:07
> 
> 
> Duplicate of #496 – unclear why #496 got closed.

The comments there explain why.

**Comment by dreamflasher** [comment] 2020-11-18 09:10
Then this issue here should be closed, too.

**Comment by dartcafe** [comment] 2020-11-18 09:10
> Then this issue here should be closed, too.

Why that?

**Comment by jacotec** [comment] 2021-02-01 22:16
+1 for this ... that's the last big missing piece in this fantastic app ;-)

**Comment by dartcafe** [comment] 2021-02-02 16:40
Good, you mention it, because, I am thinking about a concept to offer polls with user interaction and the possibility of adding options for the participants. First we need realtime change detection and date polls with a duration, which are targeted for the next version.

**Comment by dartcafe** [comment] 2021-03-25 20:01
## Added an option to allow users to add proposals.
![grafik](https://user-images.githubusercontent.com/26707476/112535676-ddcca600-8dac-11eb-84a3-b1531c7c2ea0.png)
## Also for date polls
![grafik](https://user-images.githubusercontent.com/26707476/112536015-3c921f80-8dad-11eb-8388-3e8899ca5462.png)

**Closed** 2021-03-26 06:58 UTC
Labels: enhancement
