### ISSUE TITLE
Add support for multi-day events

### ISSUE THREAD

**Issue by Yezariael** [nextcloud/polls#462] opened 2018-12-26 00:04 UTC
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to create a multi-day event, e. g. if I want to create a poll which weekend should be taken for a trip.

**Describe the solution you'd like**
A possibility to select multiple days as one event.

**Comment by v1r0x** [comment] 2018-12-26 00:13
I think in that case it would be easier to use a text-based poll. IMHO adding multi-day events is to complex to develop **and** use.

**Comment by dartcafe** [comment] 2018-12-26 08:32
Duplicate of #201 and #194

**Closed by dartcafe** 2018-12-26 08:32 UTC
Labels: duplicate
