### ISSUE TITLE
Limit right to create polls to user(groups)

### ISSUE THREAD

**Issue by dirdi** [nextcloud/polls#1106] opened 2020-09-18 08:53 UTC
**Is your feature request related to a problem? Please describe.**
Some of our (not very tech-savvy) users tend to click on the button to duplicate a poll and then vote at the clone instead of the original one. Other users also tend to vote at cloned polls and finally an administrator has to merge the votes of polls and their clones by hand.

**Describe the solution you'd like**
If would be convenient if it was possible to restrict the ability to create (and therefore duplicate existing) polls to user(groups), like it is done for [announcements](https://github.com/nextcloud/announcementcenter) (everybody can _view_ and _comment_ _on_ but only members of defined groups can _create_ announcements) or the [impersonate](https://github.com/nextcloud/impersonate) app.

**Additional context**
Since a similar feature has already [been implemented](https://github.com/nextcloud/announcementcenter/blob/e7ec8c56b0bd1b5ce8c5511d438e5802947558c9/templates/admin.php#L32) at the other mentioned apps, this code could possibly be reused and hopefully make this feature request be simple to be implemented.

**Comment by tobyps** [comment] 2020-09-18 13:46
Sounds like a Duplicate of #658 

Our users havent found that option yet, hopefully the feature gets implemented before they do ;)

**Comment by dartcafe** [comment] 2020-09-23 14:49
But duplicate to #858

**Closed** 2021-09-05 22:40 UTC
Labels: enhancement, Feature:Admin
