### ISSUE TITLE
Button position when adding new poll (Safari)

### ISSUE THREAD

**Issue by wiertz** [nextcloud/polls#770] opened 2020-01-23 08:41 UTC
### What is going wrong?
**Describe the bug**
Buttons overlay the options Poll schedule/text based

**To Reproduce**
1. Open polls (Safari)
2. Click "Add new poll"

<img width="294" alt="image" src="https://user-images.githubusercontent.com/19712668/72968794-886dc100-3dc4-11ea-8c0b-b8c84276eb30.png">

**Comment by herrmannsdorfer** [comment] 2020-01-23 08:55
Duplicate of #716

**Comment by iakiakiak** [comment] 2020-02-12 16:16
Same with "Change view" button on FireFox for Android overlaying poll title in portrait mode.

**Comment by jacotec** [comment] 2020-04-10 17:22
That does not work for me in the 1.4.0 Beta (as mentioned in #892 ). I've installed the beta and this is how it looks on my MacBook in Safari:

![image](https://user-images.githubusercontent.com/3321655/79009781-a1cf0f80-7b60-11ea-8311-bba5f7c884aa.png)

**Comment by jacotec** [comment] 2020-04-10 17:34
Also the layout does not look pretty well in Safari compared to Chrome or Firefox:

![image](https://user-images.githubusercontent.com/3321655/79010419-34bc7980-7b62-11ea-938c-f1a1693187ef.png)

**Comment by dartcafe** [comment] 2020-04-10 21:02
You are absolutly right. I fixed a similar error. I tested on macOS and changed some css. Fix is on the way.

**Closed** 2020-04-11 08:04 UTC
Labels: design, investigate
