### ISSUE TITLE
Voting is not possible after Poll edit

### ISSUE THREAD

**Issue by GAS85** [nextcloud/polls#316] opened 2018-02-22 08:24 UTC
### Steps to reproduce
1. Create and save new pool with free Text, e.g. 22.03 and 18.03
2. Somebody voted, e.g. for 18.03 also
3. Go to edit and delete 18.03 and enter 13.03 (that was a typo)
4. Nobody can select 13.03 and save a vote. It is simply dropped.

Edited: Working issue example (Voting was finished): https://gas85.ddns.net/index.php/apps/polls/poll/qNlcSB7uMtE0mJ3O

### Expected behaviour
After edit new entries should be selectable.

### Actual behaviour
If new entries are presented - no way to vote for them

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.29

**Database:** MySQL 5.7.21

**PHP version:**  7.0.25

**Nextcloud version:** 13.0.0

**Where did you install Nextcloud from:** Official Repository

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.
```

**Comment by dartcafe** [comment] 2018-02-22 19:16
I could reproduce it. I will investigate later. Seems, that there is something wrong with the appendix (_#). It is missing after I added a new poll option. I checked this against my develop version, and this error does not occur any more.

Thanks for reporting.

**Comment by dartcafe** [comment] 2018-07-17 18:40
Please test in current beta or wait until release...

**Comment by joergmschulz** [comment] 2018-07-18 20:00
Cannot reproduce in current beta 2 for 9.0. @GAS85 can you confirm and close this issue?

**Closed** 2018-07-19 04:40 UTC
Labels: bug
