### ISSUE TITLE
Disable enter email when filling a poll

### ISSUE THREAD

**Issue by huberte** [nextcloud/polls#1271] opened 2020-12-02 10:38 UTC
Would it be possible to disable the email feature ? It's confusing for my NPO old members.

Thanks.

**Comment by dartcafe** [comment] 2020-12-03 13:00
Not sure, what you referring to. This one? 
![grafik](https://user-images.githubusercontent.com/26707476/101021049-ade46300-356f-11eb-9276-a06578f07384.png)
If yes, then no, disabling is not possible. 

But I would like to learn, where or why the user is confused.

**Comment by huberte** [comment] 2020-12-03 14:43
Yep and
Suddenly today I have an error message :/ 
![image](https://user-images.githubusercontent.com/1870560/101043145-45e94900-357e-11eb-9c94-d5b599be57ee.png)

**Comment by dartcafe** [comment] 2020-12-03 18:37
Sorry for that but without further information, I cannot help here. Maybe the name you entered was used in a parallel session and saved after the check in the browser but before this input was saved. I can only guess. 

Referring to your first post. What confuses the user?

**Comment by huberte** [comment] 2020-12-03 20:54
the user said he did have to give a code or something.

Random caracters give the same results, I would like to have something as easy as a doodle. Just a name or a nick.

**Comment by dartcafe** [comment] 2020-12-04 14:27
> the user said he did have to give a code or something.
> 
> Random caracters give the same results, I would like to have something as easy as a doodle. Just a name or a nick.

I'm not sure, what you are referring to? To the error you posted or to your first post. For the error please open another issue and provide some more information (JS console and/or log file information). Otherwise it is not reproducable for me. 

Regarding to the user confusion: 
There is only the need to add a name or something else in the name field, and the vote is possible. The email address is still optional for beeing able to subscribe to notifications and recieve an invitation mail with the personal link to the poll.

**Comment by cksr9** [comment] 2020-12-10 10:35
We have the same problem. If I enter an e-mail address, the error message appears as in the screenshot above. I would like to deactivate the optional field "E-Mail". So it doesn't lead to confusion.

**Comment by dartcafe** [comment] 2020-12-10 21:47
Now I am confused. I don't understand your issues. 

The email field is optional for users, who want to get updates and or a mail with their personal link. 
If an email address is entered, the user gets a mail with the personal link and he can subscribe to update notifications. 
If no email address is entered, the user can enter the poll but cannot mail the link to himself and he cannot subscribe. 

If there is a bug, I need more information, otherwise I can't analyse the problem, because I have no errors on my systems. 
If there is a UX problem, I have to know what the user misunderstands.

What do you mean with disable? Who should disable what and how, to reach which goal?

**Comment by huberte** [comment] 2020-12-11 12:44
Just to make as easy and light as possible , just a name or a nick. Lie other poll system.
Maybe you could add the possibility in admin panel to disable the email field ?
Thanks
PS : did not resolve the issue with an "save name error" though, will write an issue

**Comment by gituser789** [comment] 2020-12-16 21:33
I agree with @huberte. 
The optional email address field should be activatable/deactivatable in the admin console.
This field is confusing for some people. And if you have not set up an email server, the field is useless because the email notifications will not work.

**Comment by dartcafe** [comment] 2020-12-17 11:07
The possibility of adding an email address for public polls was a heavily requested feature, for beeing able to get the personal link per mail and to be able to subscribe to poll notifications. 

I would heavily like to understand the following:
* Why does a field for an optional email address confuse users?
* Shouldn't it be the users's choice to add his email address or not?
* What is the use case for disabling the email address for public polls?
* What is meant with `activatable/deactivatable in the admin console`? 
  * On a per poll base?
  * Generally for the polls app or 
  * for Nextcloud?

@huberte Sending notifications doesn't have the need of setting up a mail server. Use an existing SMTP-Server or use sendmail. The notifications and invitations of polls are sent out via the core mail functions. So either your nextcloud does never send emails or there is an issue in the polls app using the core mail functions.

Maybe we have a UX issue and change the user's workflow, but adding more configurations does unnecessarily increase complexity for a limited value.

**Comment by cksr9** [comment] 2020-12-17 15:12
The problem is that this error occurs while sending the e-mail. An SMTP is stored, i.e. other Nextcloud notifications also work via email. The user then wants to enter his optional e-mail address and is then irritated if an error occurs. The users of this function are usually very technically unskilled. It is therefore desirable that the function can simply be switched off, even if it is only optional. Otherwise, I have to say with the invitation that it is not possible that there can be errors with the optional use, you just want to avoid that.

**Comment by dartcafe** [comment] 2020-12-17 16:44
> The problem is that this error occurs while sending the e-mail. An SMTP is stored, i.e. other Nextcloud notifications also work via email. The user then wants to enter his optional e-mail address and is then irritated if an error occurs.

Thanks for your effort, but I think, I understood **your** problem. Because of that I requested to open another issue and provide more information (logs), because there should be no error message.Without this information investigation and a fix are not possible, as I can't reproduce it.

This issue is a feature request for removing the email field or make it configurable.

**Comment by gituser789** [comment] 2020-12-17 21:28
yes, this issue is a feature request to make the email field configurable.

    What is meant with activatable/deactivatable in the admin console?
    * On a per poll base?
    * Generally for the polls app or
    * for Nextcloud?

Generally in the polls app (if there is no email functionality configured by the admin) and per poll (if the email functionality is working in general, but the poll creator does not want this option, e.g. due to technically unskilled people which have to fill out the poll and should net get confused by an optional field. The workflow to fill out the poll should be as easy as possible).

**Comment by dartcafe** [comment] 2020-12-18 22:04
I still see no valid use case here.

* I doubt there exist nextcloud installations without email configuration. And if, this is an edge case and will affect a lot of other apps, too.
* I am sure, that also for technically unskilled people it is no problem to tell if a field needs to be filled or not.
* The field asks for the amail address. I don't understand, what is confusing here.

Maybe the user doesn't understand, that the field can be skipped. If this is the problem, we maybe have a UX issue and we can optimize the description for the field. 

But a clear no for configuring this. The cost and the raise in complexity for implementing, testing and maintaining this is to high compared to its value.

**Comment by huberte** [comment] 2020-12-18 22:14
I disagree, We are some here, who are trying to implement GAFA alternative solutions in our associations, organization.
 When you go to doodle or some other pols, you just have to put your nick in. Basta.

Easy.

**Comment by dartcafe** [comment] 2020-12-18 22:19
Yes, But the users get no notifications on updates unless they are registered and pay. And here you can also participate while just entering your name. The email is still optional, but neccesary, if the user wants a personal link and notifications.

**Comment by NicoHood** [comment] 2020-12-19 18:48
I also have the issue and would suggest two solutions:
* The option should not be available when no smtp is configured (No, I have not set this up and I do not need it. In any case this should not be assumed, because as you can tell it does not apply to the users above. Imagine how many users are not checking this github and simply uninstall your software)
* The email notification option could be available after making the poll. Users are lazy and users do not want to read everything. The most simple usecase for the majority is: Add a name and send the poll. That is a nobrainer. Now if there is a banner/popup right after the poll that sais "Thanks for your vote, subscribe for updates", the first group of users would simply ignore and close the message and the few people interested about notifications will have an option to subscribe. (The option is only shown if smtp is configured)

This gives us:
* No additional, confusing (server side) config* 
* A fix when no smtp is configured
* Still a power user option while making it a nobrainer for the majority of users

**Comment by dartcafe** [comment] 2020-12-21 22:40
* No SMTP: Wow, didn't believe, that there are installations without SMTP configuration. But you are right, if no SMTP is configured, the email address is confusing, because of a user's expectation, which can't be fullfilled. But I fear we have more to do then, because at least sharing is relying on emails right now. We should have a separate issue for that. 

* Moving to the vote page is possible (maybe without annoying popup). Actually you are currently not able to add or change it afterwards. The current implementation is a lazy one and needs improvement. This is a design and UX topic.

**Comment by NicoHood** [comment] 2020-12-22 01:00
Nice! I am excited to see what you come up with :-)

**Comment by NicoHood** [comment] 2021-01-21 09:35
push

**Comment by dartcafe** [comment] 2021-02-15 18:57
We can close this one. See related issues

**Closed by dartcafe** 2021-02-15 18:57 UTC
