### ISSUE TITLE
Public poll constantly reloads the page

### ISSUE THREAD

**Issue by ctsde-markus** [nextcloud/polls#449] opened 2018-12-16 19:59 UTC
### What is going wrong?
**Describe the bug**
When i create a public poll and someone without account (or me, not being logged in) opens the link, the page states in a yellow popup there was a problem loading the page and it will reload it (i use the german version, so i don't know the exact english text).

If you are quick enough, your poll is actually saved, so i doubt there was a real problem loading the page. I also don't see anything in the nginx, the php-fpm or the owncloud log.

I run owncloud 10.0.10 with polls 0.8.1 (the most recent version in the marketplace).

**To Reproduce**
1. create a poll
2. create a public link for it
3. log off from you owncloud account
4. open the public link

**Expected behavior**
I'd expect the page just being loaded and that i get more time than the 5 seconds until reload to fill in.

**Screenshots**
![poll reload problem](https://user-images.githubusercontent.com/3747528/50058173-d1405880-0174-11e9-85db-f04e0cf1b585.png)

### Information about your polls installation
**Polls version?** (see apps page)
polls-0.8.1

**Fresh installation or update from a prior version (from which one)?**
fresh installation

**How did you install this version?(Appstore or describe installation)**
occ market:install polls

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
owncloud

**Which Version?**
10.0.10

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
10.0.10

**List of activated apps:**

```
Enabled:
  - activity: 2.4.0
  - calendar: 1.6.0
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - market: 0.2.5
  - notifications: 0.3.5
  - polls: 0.8.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```
**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "oc0f84c44b90",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/tmp\/php\/owncloud\/data",
        "dbtype": "mysql",
        "version": "10.0.10.4",
        "dbname": "owncloud",
        "dbhost": "web01.intern.sgd.de.cts.at",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud01.de.cts.at",
            "cloud01.sgd.de.cts.at",
            "cloud01.intern.sgd.de.cts.at"
        ],
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "signed": "true",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "18"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.4",
            "ocsid": "168708",
            "signed": "true",
            "types": ""
        },
        "core": {
            "global_cache_gc_lastrun": "1438759928",
            "installedat": "1415617762.6356",
            "lastcron": "1544989397",
            "lastupdateResult": "[]",
            "lastupdatedat": "1544989228",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "vendor": "owncloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.4.0",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.8.2",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.1",
            "types": "filesystem"
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "0.7.1",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "ocsid": "166049",
            "signed": "true",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.11.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "signed": "true",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "16.1.0",
            "signed": "true",
            "types": ""
        },
        "market": {
            "activity": "2.4.1",
            "calendar": "1.6.1",
            "contacts": "1.5.5",
            "enabled": "yes",
            "files_pdfviewer": "0.10.0",
            "files_texteditor": "2.3.0",
            "gallery": "16.1.1",
            "installed_version": "0.2.5",
            "market": "0.2.3",
            "signed": "true",
            "templateeditor": "0.4.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.5",
            "types": "logging"
        },
        "polls": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "signed": "true",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.3.1",
            "signed": "true",
            "types": ""
        },
        "updatenotification": {
            "core": "10.0.9",
            "enabled": "yes",
            "installed_version": "0.2.1",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        }
    }
}
```

### Server configuration

**Operating system**:
FreeBSD

**Web server:**
nginx

**Database:**
MySQL

**PHP version:**
php71-7.1.24

**Signing status:**

```
No errors have been found.
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Device:**
MacBook Pro mid 2014

**Browser:**
Safari 12.0.2

**Operating system:**
macOS Sierra 10.12.6

The same happens from a Debian Workstation with a recent Firefox and on my iPhone (iOS 11), so i doubt it's browser related.

#### Nextcloud log (data/nextcloud.log)
```
nothing regarding poll(s) and nothing is added when i load the public poll
```

**Comment by v1r0x** [comment] 2018-12-16 21:09
Duplicate of #448

**Closed by v1r0x** 2018-12-16 21:09 UTC
