### ISSUE TITLE
Polls shows "poll not found 404" when sending multiple request to polls

### ISSUE THREAD

**Issue by ricarD0S** [nextcloud/polls#2029] opened 2021-10-12 11:06 UTC
## What is going wrong? What did you observe?
**Describe the bug**

hey im new to this forum and i have a problem that i cant get rid off since days, hopefully i can find help here :heart:

Sometimes the survey app shows error no survey found, but when you reload or look at the survey at a later time, the survey is there again. If some people (2-3) are in the polls app and request surveys at the same time the whole frontend is very slow (pages in nc loads 40 seconds ~). 

I did everything on this site to better the perfomance: https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html
Except for Redis as a session handler for the webserver. Php-fpm is the session handler for php.

i freshly installed two instances of nc now and none of them had this issue with the polls app. it might be a problem in redis, that when he wants to deliver a page that got loaded before, it fails. but redis is running and when i monitor redis with the cli "monitor" command, i can see that the requests are getting handeled.

i can't reimplement the whole nc server because its already in a production enviroment.

**Steps to reproduce the behavior**
Steps to replicate it:

Go to all surveys in the polls app
Open up a random survey (the first survey normally loads fast)
Then go to “all surveys” again
Open up another survey (sometimes the second survey loads also fast then repeat “step 2-4”)
404 Error Survey not found page appears

Steps to replicate it 2.0:

Go to all surveys in the polls app
Open up many polls in different tabs at the same time (some of them will have the error 404)
other noticable erorrs:

the nc instance sometimes cant load avatar pictures and statuses of the user, after i switch from one survey to "all surveys" again. is my file backend broken?

**Add a screenshot of the misbehavior**

![image](https://user-images.githubusercontent.com/89484260/136938800-c1adc892-25a8-45b5-bc95-5423e48db7a0.png)
![image](https://user-images.githubusercontent.com/89484260/136939261-2c9ce7f7-3dcb-4f7b-b787-e2a11c5f999c.png)

the site seems to never finish loading.

## How should it work?
**What you expected to happen?**

that the poll is loading. 

## Information about your polls installation
**Polls version:** (see apps page)

**Fresh installation or update from a prior version (from which one)?**

- [x] First time install
- [ ] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)

Nextcloud version: Nextcloud 22.1.1
Operating system and version: Ubuntu 20.04.3 LTS
Apache or nginx version: 2.4.41
PHP version: 8.0.11
mariadb: 10.3.31
cores: 4 x 2.2 GHz
RAM: 8GB
php - memory_limit: 4 GB
timout time php: 3600
php - max data to upload: 2 MB

<details>
<summary>List of activated apps</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - admin_notifications: 1.0.2
  - announcementcenter: 6.0.0
  - auto_groups: 1.3.1
  - breezedark: 22.0.2
  - bruteforcesettings: 2.2.0
  - circles: 22.1.1
  - cloud_federation_api: 1.4.0
  - cms_pico: 1.0.16
  - collectives: 0.14.22
  - comments: 1.11.0
  - contacts: 4.0.3
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - deck: 1.5.3
  - documentserver_community: 0.1.11
  - drawio: 1.0.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_bpm: 0.2.1
  - files_fulltextsearch: 22.0.1
  - files_markdown: 2.3.4
  - files_mindmap: 0.0.25
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_texteditor: 2.14.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.3.0
  - fulltextsearch: 22.0.1
  - fulltextsearch_elasticsearch: 22.0.1
  - ldap_contacts_backend: 1.2.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - onlyoffice: 7.1.2
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.2.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - quicknotes: 0.7.2
  - recognize: 1.6.10
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - side_menu: 1.27.2
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.12.0
  - theming_customcss: 1.9.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflow_ocr: 1.22.2
  - workflowengine: 2.3.1
Disabled:
  - admin_audit
  - analytics
  - apporder
  - bbb
  - encryption
  - files_external
  - groupfolders
  - qownnotesapi
  - spreed

```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

<?php
$CONFIG = array (
  'instanceid' => 'id',
  'passwordsalt' => 'pw',
  'secret' => 'pw',
  'trusted_domains' => 
  array (
    0 => 'cloud.de',
  ),
  'allow_local_remote_servers' => true,
  'datadirectory' => '/home/data',
  'dbtype' => 'mysql',
  'version' => '22.1.1.2',
  'overwrite.cli.url' => 'https://cloud.de',
  'overwriteprotocol' => 'https',
  'htaccess.RewriteBase' => '/',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'user',
  'dbpassword' => 'pw',
  'default_phone_region' => 'DE',
  'default_language' => 'de',
  'default_locale' => 'de',
  'installed' => true,
  'app_install_overwrite' => 
  array (
    0 => 'files_bpm',
    1 => 'dropit',
    2 => 'epubreader',
    3 => 'zimbradrive',
    4 => 'talk_simple_poll',
    5 => 'admin_notifications',
    6 => 'announcementcenter',
    7 => 'dashboardcharts',
    8 => 'ldapcontacts',
    9 => 'social',
    10 => 'files_fulltextsearch_tesseract',
  ),
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/run/redis/redis-server.sock',
    'port' => 0,
    'password' => 'pw',
    'dbindex' => 0,
    'timeout' => 1.5,
  ),
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'maintenance' => false,
  'loglevel' => '2',
  'remember_login_cookie_lifetime' => '1800',
);

</details>

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
just old log entries and nothing about polls.
```
</details>

<details>
<summary>Browser console log</summary>

![image](https://user-images.githubusercontent.com/89484260/136943610-65f5381a-0b74-4404-8d4f-ab4bd6d0bc8a.png)

</details>

**Comment by ricarD0S** [comment] 2021-10-15 09:15
> Set the logging level to `verbose` instead of `defaut levels` (upper right corner of console) Im a curious if the background watching is breaking.
thanks, i found it

![image](https://user-images.githubusercontent.com/89484260/137445954-f92a7ea5-ddf7-4d64-82ae-85ca22ece559.png)

this appears, when the '404 poll not found' page appears

while i do nothing interactive on the page this appears in the console:

![image](https://user-images.githubusercontent.com/89484260/137447926-81799a95-2776-4ff9-ac28-1730d00c0aa2.png)

> Polls tries to request data from the backend via AJAX request, but it seems, the requests are terminated by the backend. The get line gets a protocol error and in the result, the AJAX requests throws an error (easy explanation).
thank you for explaining, that makes sense :)

> But in the end I still believe it is a configuration issue, otherwise we would have more issue reportings like that.
i think so too and im very glad, that you are helping me with that. i'm in despair since weeks now... 
but i think we are getting closer :)

at one time (couldnt reproduce this error) the log said that it didnt found an avatar picture in the dedicated path, but when i looked the path up, the picture was available. pretty weird, but just a side note.

----

while it says "net::ERR_HTTP2_PROTOCOL_ERROR" everytime, i'm going to my http2 configuration once again.
i configured http2 like in this tutorial https://www.tecmint.com/enable-http2-in-apache-on-ubuntu/ 
(just with php8.0 instead of 7.4)

whats weird is that the test 'curl -I --http2 -s https://mydomain.de/ | grep HTTP' (url is changed up here) at the end on the tutorial site doesn't bring up the wanted result 'HTTP/2 200'. the module http2 is activated ('php -m' doesnt show the module, but when im trying to activate it, it says that its already enabled???) and php8.0-fpm is up and running, also the virtualhost conf looks fine.

**Comment by melkon** [comment] 2021-10-17 11:30
We're encountering the same / a similar issue with the polls app on two different nextcloud instances. We're on rather limited hardware on both - one is for personal use while the other is for a group of 30 people, but usage isn't normally not an issue. However, we recently held a meeting where everybody had to use the polls app at the same time and the server got unresponsive.

Looking into the issue, I tried to reproduce the problem with just opening a couple of polls at the same time (like 10 tabs or so) and even though the first tabs were loading fine, the rest got stuck and the whole nextcloud instance (so also other apps like files) were not able to load anymore. After closing the tabs the server got back to normal slowly. Opening many tabs of any other app (like files, calendar etc ...) did not result in any usage issues.

Since I have control over one instance (not the other, unfortunately), the php-fpm log was silent while opening the other apps, but went nuts when opening the polls app (as it tried to create more children, but the max (15) was instantly reached). No other logs showed any error.

nginx / php8-fpm / pgsql 13.4

1 CPU / 2GB  RAM
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 100 MB

**Comment by melkon** [comment] 2021-10-18 08:32
The hardware challenge is only something I was thinking about, but I don't see why there should be any.

As every client was polling every second, everything was fine. The instance itself was still properly usable. I agree the round trip from the client to the server including session validation each second feels like an unnecessary overhead, but at least that keeps my instances running properly, so something is amiss and I agree we should figure out the actual issue.

Until then, an option for disabling real-time updates would be a nice workaround.

Onto the reproduction of the issue itself:
I quickly installed a nextcloud:fpm docker env with an docker-compose taken from [here](https://hub.docker.com/_/nextcloud)

```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:fpm
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
```

with [this nginx.conf](https://github.com/nextcloud/docker/blob/652416e6513372951afaaed5cd45cf92ce8ec198/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf) taken from the nextcloud dockerhub example repository.

- booted it up
- selected sqlite (mariadb wasn't working for whatever reason, something related to innodb, unfortunately I have no time right now to dive into the topic)
- installed nextcloud & polls app
- created one text poll with two options
- opened this poll in like many tabs (10 - 20) (but even just opening three to four created the issue)
- the first were fine, then everything got stuck, instance was very slow / unusable.

All those issues are gone when disabling the while-sleep in the WatchController even though the frontend communicated now multiple times / second with the server.

Maybe that helps you to reproduce the issue locally on your end?

**Comment by ricarD0S** [comment] 2021-10-18 08:59
> I am definitely at an end with my knowledge. Have you tried another browser?
> 
> Some issues with `net::ERR_HTTP2_PROTOCOL_ERROR` seem to be Chrome related (i.e. [icing/mod_h2#190](https://github.com/icing/mod_h2/issues/190))

i have the same issue in firefox unfortunately... 

> Anyway, I removed the sleep and the while-loop, and even though the frontend did now a request every second, it was still responsive compared to the sleep via server. However, I'm not sure if there is another fix for hardware-limited systems / better implementation in general. Or do you have any idea which configuration option might affect the handling? (since the author wasn't able to reproduce the issue on a fresh installation).
> 
> @ricarD0S, maybe you can try that on your sever as well and see it we are indeed encountering the same issue?

THANK YOU! This seemed to help. I uncommented Lines 58,59 and 61 and now it's loading fast and the '404 poll not found' doesn't seem to appear when trigerring many requests :)

**Comment by dartcafe** [comment] 2021-10-30 09:41
First try. Seems to work, but needs testing #2060

**Comment by melkon** [comment] 2021-11-02 09:14
Hmm, I don't get the PR working on my server. When I git-clone the project (and set the rights and call occ:enable polls) - polls shows up but the app settings are the ones from 3.3.0. I'm not familiar with the process of installing an app from git directly vs from the store otherwise I would've checked it if that resolves the issue.

**Comment by dartcafe** [comment] 2021-11-02 12:48
You have to compile the js stuff first. See [README.md](https://github.com/nextcloud/polls#installation--update). 

I can make a beta version for manuall install, when I merged the PR. I am testing some things, because I found some unwanted side effects. Hope I am finished now. ;-)

**Comment by dartcafe** [comment] 2021-11-02 20:28
Try the attached version. 
1. Delete the polls folder in the app folder
2. Extract the containing folder into your apps folder

See changelog for the contained changes

[polls-3.4.0-alpha1.zip](https://github.com/nextcloud/polls/files/7463817/polls-3.4.0-alpha1.zip)

**Comment by melkon** [comment] 2021-11-03 06:31
> You have to compile the js stuff first. See [README.md](https://github.com/nextcloud/polls#installation--update).

Ah, I forgot that I did that as I was installing the app in my local docker env. Shame on me. However, I tried the PR on my server where I don't want to install dev-dependencies (and then my time for trying to get it running was over :-().

> Try the attached version.
>     1. Delete the polls folder in the app folder
>     2. Extract the containing folder into your apps folder
> 
> See changelog for the contained changes
> 
> [polls-3.4.0-alpha1.zip](https://github.com/nextcloud/polls/files/7463817/polls-3.4.0-alpha1.zip)

Thanks! I installed it and I wasn't able to reproduce the issue anymore when I switched to "use client polling"  :+1: 

One note, not sure if it's related to the alpha installation: no performance option was selected as I opened the settings for the first time. I assume long polling is the default and thus should be visually enabled, should it not?

**Comment by dartcafe** [comment] 2021-11-03 07:27
> One note, not sure if it's related to the alpha installation: no performance option was selected as I opened the settings for the first time. I assume long polling is the default and thus should be visually enabled, should it not?

It should. I will check it later. Thanks for testing and reporting. Glad, that it seems to work on your side.

**Comment by dartcafe** [comment] 2021-11-03 16:54
The default will now be used. I will merge the PR.

**Closed** 2021-11-03 16:54 UTC
Labels: enhancement
