### ISSUE TITLE
Mostly hidden description when creating a new poll

### ISSUE THREAD

**Issue by tYYGH** [nextcloud/polls#230] opened 2017-11-01 17:47 UTC
### Steps to reproduce
1. Create new poll

### Expected behaviour
See description.

### Actual behaviour
Mostly hidden description. Here I typed some random text so that you can see the spell-checker underlining in red:
![image](https://user-images.githubusercontent.com/5556825/32288624-ca44a9b0-bf34-11e7-869c-7ebc90369ac8.png)

### Server configuration

**Operating system**: up-to-date Archlinux

**Web server:** Nginx 1.13.5 + uwsgi 2.0.15

**Database:** Postgresql 9.6.5

**PHP version:** 7.1.11

**Nextcloud version:** 12.0.3

**Where did you install Nextcloud from:** Updated from previous version of Nextcloud, originally updated from ownCloud 9 (IIRC).

**Signing status:**
**List of activated apps:**
**Nextcloud configuration:**
See here: https://github.com/nextcloud/server/issues/7037

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Problem seen in both Firefox and Chromium

**Operating system:** up-to-date Archlinux

#### Nextcloud log (data/nextcloud.log)
```
# journalctl -n 0 -f _SYSTEMD_UNIT=uwsgi@nextcloud.service
-- Logs begin at Sun 2017-09-24 19:10:12 CEST. --
nov. 01 18:25:21 sphinx3 ownCloud[19499]: {lib} ResourceLocator can not find a web root (root: /var/lib/nextcloud/apps/polls, file: index.php/css/polls/fd255ae37aa59fba53b3cbd164554418-main.css, webRoot: , throw: true)
nov. 01 18:25:21 sphinx3 ownCloud[19499]: {lib} ResourceLocator can not find a web root (root: /var/lib/nextcloud/apps/polls, file: index.php/css/polls/fd255ae37aa59fba53b3cbd164554418-createpoll.css, webRoot: , throw: true)
nov. 01 18:25:21 sphinx3 uwsgi[19223]: [pid: 19499|app: -1|req: -1/156] 192.168.1.99 () {66 vars in 1463 bytes} [Wed Nov  1 18:25:20 2017] GET /index.php/apps/polls/create => generated 36776 bytes in 414 msecs (HTTP/1.1 200) 12 headers in 799 bytes (0 switches on core 0)
nov. 01 18:25:21 sphinx3 uwsgi[19223]: [pid: 19499|app: -1|req: -1/157] 192.168.1.99 () {58 vars in 1499 bytes} [Wed Nov  1 18:25:21 2017] GET /xapps/polls/css/jquery.datetimepicker.css?v=cc55457f0279f2b689e723df6ceea9a6-3 => generated 18420 bytes in 0 msecs via offload() (HTTP/1.1 200) 4 headers in 152 bytes (0 switches on core 0)
nov. 01 18:25:23 sphinx3 uwsgi[19223]: [pid: 19499|app: -1|req: -1/158] 192.168.1.99 () {58 vars in 1424 bytes} [Wed Nov  1 18:25:23 2017] GET /xapps/polls/js/create_edit.js?v=cc55457f0279f2b689e723df6ceea9a6-3 => generated 20651 bytes in 0 msecs via offload() (HTTP/1.1 200) 4 headers in 166 bytes (0 switches on core 0)
nov. 01 18:25:23 sphinx3 uwsgi[19223]: [pid: 19499|app: -1|req: -1/159] 192.168.1.99 () {58 vars in 1519 bytes} [Wed Nov  1 18:25:23 2017] GET /xapps/polls/js/jquery.datetimepicker.full.min.js?v=cc55457f0279f2b689e723df6ceea9a6-3 => generated 54172 bytes in 0 msecs via offload() (HTTP/1.1 200) 4 headers in 166 bytes (0 switches on core 0)
```

#### Browser log
All requests have status 200, with ~50% read from the browser cache.

**Comment by tYYGH** [comment] 2017-11-02 11:31
Some more information: While all actual requests do have the status 200, it seems that some requests are missing, due to *Content Security Policy*; I had missed that in the browser console:

```
Content Security Policy:
 La source dupliquée « 'unsafe-inline' » a été ignorée.    (source inconnue)
Content Security Policy:
 Impossible d’analyser l’hôte invalide 'unsafe-inline'     (source inconnue)
Content Security Policy:
 La directive « frame-src » est obsolète. Veuillez utiliser
 la directive « child-src » à la place.                    (source inconnue)
Content Security Policy:
 Les paramètres de la page ont empêché le chargement d’une
 ressource à self (« script-src 'nonce-L1dHL0JXeDg1VzI3Kz…
 …lJT0o4TXlqdmxGRldoRVNwc1JvOXpUbUZma3FmZz06dVJQelZoMDZxV…
 …WJXdllOWVZQSjR5YzkxUUFBMGY3UXBtNjZVd1h5dXk2QT0='
 'unsafe-eval' »). Source: (function (ERROR) {
    const V8_STACK_....                                    polls:1
```
As things stand, Polls is plain ugly, to the point of being barely usable (you have to guess where you are expected to click…). I suppose some CSS is missing.

Some vocabulary:
* “la source dupliquée … a été ignorée” => “the duplicated source … has been ignored”
* “source inconnue” => “unknown source”
* “d’analyser l’hôte invalide” => “to analyse the invalid host”
* “La directive … est obsolète. Veuillez utiliser la directive … à la place” => “The … directive is obsolete. Please use the … directive instead”
* “Les paramètres de la page ont empêché le chargement d’une ressource à self” => “The parameters for the page kept a resource to self from being loaded” (?… strange sentence…)

**Comment by dartcafe** [comment] 2017-11-02 17:10
Seems, that the css is not loaded properly. If a forced browser reload does not help, please try to delete the css (not the scss) files in the apps css directory.

**Comment by tYYGH** [comment] 2017-11-02 17:32
@dartcafe, no-cache reloading does nothing.
I tried removing all (5) css files, but it gets worse. But then, it is to be expected because URLs ending in “.css” are served as files directly by the web server, so these files must exist beforehand.

**Comment by dartcafe** [comment] 2017-11-02 17:54
The css files are only delivered because of compatibility to NC prior to 12 and OC. Since NC 12, there is a scss compiler build in, which generates the css files on change of the scss files. 

I cannot reproduce this issue. Does the browser console present any errors?

**Comment by tYYGH** [comment] 2017-11-03 13:11
@dartcafe, the errors I have are in my 2nd message, and seem to be about Content Security Policy.

**Comment by tYYGH** [comment] 2017-11-03 13:32
I tried completely disabling the HTTP Content-Security-Policy header, but this does not solve the problem: now the Firefox console has neither error nor warning, and still all requests have the status code 200 (and I ran that with no browser cache), but the UI remains the same, with missing CSS, somehow…
Besides, I ran the same test in Chromium (rather pristine since I “never” use it), and I get the exact same result, with one minor difference: Chromium’s console warns me that the URL https://yalis.fr/nc/core/img/manifest.json returns an empty document; I don’t know if this can affect the Polls app.

**Comment by dartcafe** [comment] 2017-11-04 10:25
I am not sure, if the HTTP Content-Security-Policy has any relationship to this issue, but I don't want to state it for sure.

In your server log, you have an error on the files
`/css/polls/fd255ae37aa59fba53b3cbd164554418-main.css` and 
`/css/polls/fd255ae37aa59fba53b3cbd164554418-createpoll.css` which seems to be a problem indicator of creating the css files out of the scss files. 

Did you try to remove the scss files and force using the delivered css files? 
BTW: A console log of the browser could help.

**Comment by tYYGH** [comment] 2017-11-04 11:21
@dartcafe I agree with you that the CSP errors are not related to my CSS problem (see https://github.com/nextcloud/polls/issues/230#issuecomment-341704111).
As for the browser console logs, I _did_ gave them! (see https://github.com/nextcloud/polls/issues/230#issuecomment-341394002); they’re not much help, though…

The issue indeed probably lies with these 2 errors in the server logs, as you pointed out. More specifically: “`ResourceLocator can not find a web root`” (said `webRoot` being shown as empty further in the lines). I have no idea what this means, or where this `webRoot` does come from…

I was not optimistic about the test you suggested because files `fd255ae37aa59fba53b3cbd164554418-main.css` and `fd255ae37aa59fba53b3cbd164554418-createpoll.css` do not exist in my installation:

```
# find . -iname '*css' -print
./css
./css/createpoll.css
./css/createpoll.scss
./css/jquery.datetimepicker.css
./css/list.css
./css/list.scss
./css/main.css
./css/main.scss
./css/vote.css
./css/vote.scss
```

And yet, it _did_ work! With the `*.scss` files out of the way, the Polls app renders perfectly well :-) During this test:
* In the browser console, nothing but the unrelated CSP errors.
* In the server logs: nothing but uwsgi’s kind-of `access.log`-type output…

What do you think? Solved, or merely circumvented?

**Comment by dartcafe** [comment] 2017-11-04 12:29
I assume the problem is located in your installation.

NC generates the css files out of the apps scss files and access them via a redirect or any comparable method. You will not find these in the apps css folder, but under data/appdata_[someRandomString]/css/polls/ 

You can check, if the data folder and all it's subfolders are writable by the webserver's owner.

Judging from your small screenshot, I guess there are some cached css files loaded. But this all speculating from me. I fear, we cannot solve this problem, if we will keep the scss files.

**Comment by tYYGH** [comment] 2017-11-05 14:29
My config contains this, where apps are concerned:

```
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/nc\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/nc\/xapps",
                "writable": true
            }
        ],
```

The first path contains apps from the upstream distribution of Nextcloud, while the second path contains apps that I added by enabling them in the Web UI. This latter path is where Polls is installed, and was entirely written by Nextcloud itself, so it is entirely writeable.

I wonder if the scss→css process does not try and write files to the first path, that is read-only…

**Comment by dartcafe** [comment] 2017-11-21 10:56
We should think about switching to static css, instead of scss files, als long as these installation profiles are not supported properly. I close this and open a new issue.

**Comment by tYYGH** [comment] 2017-11-23 08:37
This is probably related to https://github.com/nextcloud/server/issues/5289

**Comment by splitt3r** [comment] 2017-11-27 10:12
See https://github.com/nextcloud/polls/issues/250#issuecomment-347130817

**Closed by splitt3r** 2017-11-27 10:12 UTC
Labels: bug, server
