### ISSUE TITLE
Polls 3.8.0 & 3.8.1 - No sending of invitation emails possible. Causes only error messages.

### ISSUE THREAD

**Issue by stepka0815** [nextcloud/polls#2602] opened 2022-09-24 08:00 UTC
## What is going wrong? What did you observe?
Sending invitation emails causes only error messages. No e-mails will be sent.

A clear and concise description of what is wrong.

**Steps to reproduce the behavior**
1. Click on "Send invitation email".
2. See error message(s).

**Add a screenshot of the misbehavior**
![grafik](https://user-images.githubusercontent.com/93402363/192086170-a2a21b89-a91d-44da-ad9f-0249c7193afc.png)

## How should it work?
**What you expected to happen?**

Click on "Send invitation email" should cause sending invitation email(s)

## Information about your polls installation
**Polls version:** (see apps page)
Polls 3.8.0 & 3.8.1

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: 3.7.0

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud Version: 24.0.5

<details>
<summary>List of activated apps</summary>

Accessibility			1.10.0		
Brute-force settings		2.4.0		
Calendar				3.5.0		
Circles				24.0.1		
Collaborative tags		1.14.0		
Comments			1.14.0		
Contacts Interaction		1.5.0		
Dashboard			7.4.0		
Deck				1.7.1		
Deck Import From Trello	1.0.2		
Deleted files			1.14.0		
Federation			1.14.0		
File sharing			1.16.2		
Group folders			12.0.1		
Log Reader			2.9.0		
Monitoring			1.14.0		
Nextcloud announcements	1.13.0		
Notifications			2.12.1		
Ownpad				0.6.18		
Password policy		1.14.0		
PDF viewer			2.5.0		
Photos				1.6.0		
Polls					3.8.1		
Privacy				1.8.0		
Right click			1.3.0		
Share by mail			1.14.0		
Support				1.7.0		
Talk					14.0.5		
Text					3.5.1		
Update notification		1.14.0		
Usage survey			1.12.0		
User status			1.4.0		
Versions				1.17.0		
Video player			1.13.0

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
No access!

</details>
<details>
<summary>Nextcloud Configuration</summary>
```
Sorry, but I don't know further Nextcloud Configuration data than the version number 24.0.5

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)
<!--
You can use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate
-->

**Database:**
- [x] MySql version: 10.2.36
- [ ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [x] 7.4.30
- [ ] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No!

### Client configuration
**Device:** <!-- Put an x between the brackets ([x]) or check these boxes after you created the issue -->
- [x] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** <!-- Add your Browser's version and put an x between the brackets ([x]) or check these boxes after you created the issue -->

- [x] Firefox version:
- [ ] Chrome version:
- [ ] Safari version:
- [x] Other (add name and version): Brave version 1.43.93

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>
Sorry, but there are no logs available! 
```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

I am sorry, but I don't know how to generate this.

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment] 2022-09-24 12:28
Could not reproduce this error. 

To understand what happens, I need some logging information from the browser console and/or server log.

**Comment by stepka0815** [comment] 2022-09-24 16:51
Here the browser console log with chrome:

![grafik](https://user-images.githubusercontent.com/93402363/192109594-c4c5f011-7b57-4908-aa60-e8e3da9885cc.png)

**Comment by dartcafe** [comment] 2022-09-25 05:44
OK. Thanks. For some reason, the backend could not send the invitation. The cause can be found in the server log.

Possible reasons:
* email address invalid (warning in log)
* system error on sending mails (error in log)
* ...

**Comment by stepka0815** [comment] 2022-09-25 08:35
Thanks for your feedback. 
As I just found out, the mail sending also does not work when resetting a password.
Since I have no direct access to the server log file with this system, I will contact the provider in the coming week to further clarify the issue. As soon as I have new information, I will get back to you.

**Comment by dartcafe** [comment] 2022-09-25 13:37
Check the admin setting under `Basic settings`, if the email configuration is working.

**Comment by dartcafe** [comment] 2022-09-25 13:38
Since this seems to be a system configuration error and no polls bug, I close this issue here.

**Closed by dartcafe** 2022-09-25 13:38 UTC

**Comment by stepka0815** [comment] 2022-09-27 16:20
I was able to solve the problem on the backend side. 
Thanks for your support!
