### ISSUE TITLE
3-dot menu opens at the wrong poll

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#1626] opened 2021-05-19 12:31 UTC
### What is going wrong?
**Describe the bug**
It seems the 3-dot menu is displayed at the wrong poll if your poll list is larger than the screen and a poll is clicked that is outside the initial view (after scrolling down).

**To Reproduce**
1. Open the polls overview with more polls then fit the screen (tested in the administration view, but probably affects all views)
2. Click the 3-dot menus (all work)
3. Scroll down a bit and click the menu on a previously not displayed poll
4. The menu opens at the last poll displayed on the initial (unscrolled view).

**Expected behavior**
Menu opens at correct poll

**Screenshots**
The grey menu button has been clicked
![Screenshot_Umfragen - Verwaltung_anon](https://user-images.githubusercontent.com/29312856/118812399-597b3880-b8ae-11eb-9179-d141ce19c1f7.png)

### Information about your polls installation
**Polls version?** (see apps page)
1.8.3

**Fresh installation or update from a prior version (from which one)?**
Update from ?

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud

**Nextcloud version:** (see Nextcloud admin page)
20.0.9

**Comment by dartcafe** [comment] 2021-05-19 17:51
@skjnldsv Seems to be an issue in the actions or popover component!?

**Comment by skjnldsv** [comment] 2021-05-26 13:40
Make sure the open variable is really on the right item, if so, then it's just a position issue.
You can play with the boundary prop if there is a weird positioning on the list

**Comment by dartcafe** [comment] 2023-09-06 21:08
Can't reproduce this anymore. Assume fixed in nextcloud-vue

**Closed by dartcafe** 2023-09-06 21:08 UTC
Labels: investigate
