### ISSUE TITLE
allowed number of responses

### ISSUE THREAD

**Issue by nchTOD** [nextcloud/polls#1309] opened 2020-12-23 05:51 UTC
**Is your feature request related to a problem? Please describe.**
At the moment, the user can choose several options for answering the poll. This is not always convenient, often the answer should be only one.

**Describe the solution you'd like**
In the survey settings, specify the number of responses to choose from, 1 or more

**Comment by dartcafe** [comment] 2020-12-28 12:14
Duplicate of #738

**Closed by dartcafe** 2020-12-28 12:14 UTC
Labels: duplicate
