### ISSUE TITLE
Can not choose answers again after "clicking to no" 

### ISSUE THREAD

**Issue by xfivesao** [nextcloud/polls#2402] opened 2022-05-02 07:01 UTC
## What is going wrong? What did you observe?
`Exception: Call to undefined method OCA\Polls\Model\Acl::getIsVoteLimitExceeded() in file '/var/www/vhosts/xxxx.xx/cloud.xxxxx.xxx/apps/polls/lib/Service/VoteService.php' line 108
`
**Steps to reproduce the behavior**
In case of clicking "yes", "perhaps" and "no" I can not choose after "no" again "yes".
The above error will occur... No limits activated.

**Add a screenshot of the misbehavior**

## How should it work?
After "no" I expect to choose the complete range of answers again...

A clear and concise description of

## Information about your polls installation
**Polls version:** 3.6.1

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: all versions from nextcloud repository

**How did you install this version?(Appstore or describe installation)**

- [ ] Installed from the appstore
- [x] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** Nextcloud Hub II 23.0.4
<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [x] MariaDB version: 10.6
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [x] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** 
- [ ] PC
- [x] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [x] Firefox version: newest
- [x] Chrome version: newest
- [x] Safari version: newest
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment] 2022-05-02 20:17
Please add some logging information

**Comment by xfivesao** [comment] 2022-05-02 20:27
Here is a complete log:
`Exception: Call to undefined method OCA\Polls\Model\Acl::getIsVoteLimitExceeded() in file '/var/www/vhosts/xxxx.com/cloud.xxxx.com/apps/polls/lib/Service/VoteService.php' line 108
/var/www/vhosts/xxxx.com/cloud.xxxx.com/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/index.php - line 36:
OC::handleRequest()
Verursacht durch Error: Call to undefined method OCA\Polls\Model\Acl::getIsVoteLimitExceeded()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/apps/polls/lib/Service/VoteService.php - line 127:
OCA\Polls\Service\VoteService->checkLimits()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/apps/polls/lib/Controller/VoteController.php - line 66:
OCA\Polls\Service\VoteService->set()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/apps/polls/lib/Controller/ResponseHandle.php - line 42:
OCA\Polls\Controller\VoteController->OCA\Polls\Controller\{closure}("*** sensiti ... *")
/var/www/vhosts/xxxx.com/cloud.xxxx.com/apps/polls/lib/Controller/VoteController.php - line 67:
OCA\Polls\Controller\VoteController->response()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Polls\Controller\VoteController->set()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/xxxx.com/cloud.xxxx.com/index.php - line 36:
OC::handleRequest()`

**Comment by dartcafe** [comment] 2022-05-02 20:29
Please check your installation. The log line misses the method `acl::getIsVoteLimitExceeded()`.

But it is here:
https://github.com/nextcloud/polls/blob/833248ac94589c118d06adf2db2a19b1b53d40a0/lib/Model/Acl.php#L263

Possibly the update was interrupted or something else happened. 

You can delete the app and install again from the appstore.

**Comment by xfivesao** [comment] 2022-05-02 20:33
I have deleted the app und after reinstall from app store -> same behavior.

Should I delete the app folder?

**Comment by xfivesao** [comment] 2022-05-02 20:41
same error after deleting and reinstall... 
Can there be a connection with an old survey in the database?

**Comment by xfivesao** [comment] 2022-05-02 20:48
`CREATE TABLE `oc_polls_polls` (
  `id` int(11) NOT NULL,
  `type` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT 'datePoll',
  `title` varchar(128) COLLATE utf8mb4_bin DEFAULT '',
  `description` text COLLATE utf8mb4_bin DEFAULT NULL,
  `owner` varchar(256) COLLATE utf8mb4_bin DEFAULT '',
  `created` int(11) NOT NULL DEFAULT 0,
  `expire` int(11) NOT NULL DEFAULT 0,
  `deleted` int(11) NOT NULL DEFAULT 0,
  `access` varchar(1024) COLLATE utf8mb4_bin NOT NULL DEFAULT 'hidden',
  `anonymous` int(11) NOT NULL DEFAULT 0,
  `allow_maybe` int(11) NOT NULL DEFAULT 1,
  `vote_limit` int(11) NOT NULL DEFAULT 0,
  `show_results` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT 'always',
  `admin_access` int(11) NOT NULL DEFAULT 0,
  `important` int(11) NOT NULL DEFAULT 0,
  `option_limit` int(11) NOT NULL DEFAULT 0,
  `allow_comment` int(11) NOT NULL DEFAULT 1,
  `hide_booked_up` int(11) NOT NULL DEFAULT 1,
  `allow_proposals` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT 'disallow',
  `use_no` int(11) NOT NULL DEFAULT 1,
  `proposals_expire` int(11) NOT NULL DEFAULT 0,
  `misc_settings` text COLLATE utf8mb4_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;

--
-- Daten für Tabelle `oc_polls_polls`
--

INSERT INTO `oc_polls_polls` (`id`, `type`, `title`, `description`, `owner`, `created`, `expire`, `deleted`, `access`, `anonymous`, `allow_maybe`, `vote_limit`, `show_results`, `admin_access`, `important`, `option_limit`, `allow_comment`, `hide_booked_up`, `allow_proposals`, `use_no`, `proposals_expire`, `misc_settings`) VALUES
(5, 'datePoll', 'RO Teilname SLG PP', 'Bitte die - voraussichtliche - Teilnahme an den IPSC-Trainings eintragen... \n\nVielen Dank!', 'wolf', 1647070107, 0, 0, 'hidden', 0, 1, 0, 'always', 0, 0, 0, 0, 1, 'disallow', 1, 0, '{\"autoReminder\":true}');
`

**Comment by xfivesao** [comment] 2022-05-02 20:49
Structure and ID 5 seems to be "normal" - from my point of view. But I am not a programmer... ;-)

**Comment by dartcafe** [comment] 2022-05-03 05:47
I can't see any reason. The only thing is, that NC23 does not support MariaDB 10.6. But I can't imagine, that something relating the database could be the cause. Especially because it looks normal IMHO.

**Comment by xfivesao** [comment] 2022-05-03 06:00
After reinstalling and deploying a test poll I am unable to click "anything" in the new poll...
Error is the same.

Permissions are double checked and ok. Any suggestions ;-) ?

**Comment by xfivesao** [comment] 2022-05-03 06:16
OK, that is strange. After rebooting the server everything works as expected!

Thanks for your assistance and clear statements.

**Comment by dartcafe** [comment] 2022-05-03 06:26
I checked the issue with several installations, I manage. I can't reproduce the error. 
The thrown error `Call to undefined method OCA\Polls\Model\Acl::getIsVoteLimitExceeded()` says, the method `getIsVoteLimitExceeded()` is not defined the class `Acl`. 

But it is. Maybe it is a caching problem on the server side?

**Comment by dartcafe** [comment] 2022-05-03 06:30
> OK, that is strange. After rebooting the server everything works as expected!

Great. So the caching idea could be a hit.

**Comment by xfivesao** [comment] 2022-05-03 06:57
I am using only opcache as cache for my nextcloud instance.

**Comment by dartcafe** [comment] 2022-05-03 07:11
I am only guessing since I have no experiance in this configurations. But glad, that the issue could be solved, so I can close it.

**Closed by dartcafe** 2022-05-03 07:11 UTC
