### ISSUE TITLE
Import Options via CSV

### ISSUE THREAD

**Issue by Chudlight** [nextcloud/polls#3143] opened 2023-11-04 19:23 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a poll creator, I'd like to be able to import a CSV with the poll options because this would save time. 

I receive a list of possible dates every month (ca. 15-20 possibilities per month) that currently need to each be added manually. Each option is 1 hour long at different times per day (sometimes multiple times per day).

### Describe possible solutions

Three possible solutions:
 - Allow the poll creator to fill out a table with values (using the TAB button to make the entry quicker)
 - Allow the poll creator to import a CSV table with the desired options
 - Graphical interface (click and drag on a calendar to create individual options)

**Comment by Chudlight** [comment] 2023-11-04 19:40
An additional feature request would be a "location" field for each option.

**Comment by dartcafe** [comment] 2023-11-07 18:15
I would say this is a duplicate of https://github.com/nextcloud/polls/issues/2371 - Still pending

location field for each option is much too much work for this edge case.

**Closed** 2023-11-07 18:17 UTC
Labels: enhancement
