### ISSUE TITLE
 DbalException An exception occurred while executing a query: Undefined column: 7 ERROR: column "deleted" does not exist after update to 28.0.2 RC3

### ISSUE THREAD

**Issue by rnaujack** [nextcloud/polls#3277] opened 2024-01-29 06:46 UTC
### Steps to reproduce
1. updated AIO from 27.0 stable to 28.0.2 RC3
2. in the logs comes daily the error message 

### Expected behavior 
No errors afetr update

### Actual behavior 

daily error log entries like this:

DbalException An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR: column "deleted" does not exist LINE 1: DELETE FROM "oc_polls_comments" WHERE ("deleted" > $1) AND (... ^
Error while running background job (class: OCA\Polls\Cron\JanitorCron, arguments: ) 

### Host OS 

0e9d7ca4e7bc

Betriebssystem: Linux 5.10.0-23-amd64 x86_64

Prozessor: Common KVM processor (6 cores)

Speicher: 7.76 GB

#### Nextcloud AIO version 
28.0.2 RC3

#### Current channel 
switched from stable to beta and forced update from NC 27 to NC 28

**Comment by dartcafe** [comment] 2024-01-29 14:15
Please reopen [here](https://github.com/nextcloud/polls/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml) and provide the requested informations.

**Comment by small1** [comment] 2024-01-30 10:00
The fix for this is already in the code https://github.com/nextcloud/polls/commit/692ae15eb24dfd929a7d7be3df0c9cdd2f9f6fb8 

So waiting for the next release :)

**Comment by dartcafe** [comment] 2024-01-30 15:45
Same initial thought by me too, but the error message tells something different.
Affected table here is `oc_polls_comments`. The fix just corrected a query syntax error for the `oc_polls_polls` table.

**Comment by small1** [comment] 2024-01-30 16:05
The fix is in the code. But not released yet.

**Comment by dartcafe** [comment] 2024-01-30 16:23
As I said, it seems to be different bug.

**Comment by small1** [comment] 2024-01-30 16:34
Noted that now :)

**Comment by XueSheng-GIT** [comment] 2024-02-04 13:24
Getting the same error on NC 28.0.2 and polls 6.0.1.

**Comment by dartcafe** [comment] 2024-02-09 06:40
I assume the cause is the same as #3298

**Closed by dartcafe** 2024-02-09 06:41 UTC
Labels: bug, 0. needs triage
