### ISSUE TITLE
Wrong Usernames if AD/LDAP used

### ISSUE THREAD

**Issue by hexxter** [nextcloud/polls#797] opened 2020-01-29 15:28 UTC
Polls 1.1.6
NC 17.0.2

After upgrade to a new Polls Version for all username in the polls is the sid used (ID in the AD/LDAP DB) shows like this 74C55A2C-BE2E-4EE5-8191-26B05EBD5C66.

I have not start an new poll it was an old poll and works perfekt on a old version and now all names show as sid.

BR Hexxter

**Comment by herrmannsdorfer** [comment] 2020-01-29 15:33
Duplicate of #715

**Closed** 2020-01-29 15:38 UTC
Labels: duplicate
