### ISSUE TITLE
Public link doesn't work in Firefox

### ISSUE THREAD

**Issue by haplo** [nextcloud/polls#1503] opened 2021-03-25 10:00 UTC
### What is going wrong?
**Describe the bug**
Clicking "Add a public link" in Firefox creates the link but it's never shown. Opening the same poll in Chromium displays the created links.

**To Reproduce**
1. Create a new poll, add options.
2. Go to "Shares" *in Firefox*.
3. Click on "Add a public link"
4. No effect at all: no UI change, no error message. Reloading doesn't show any public links.

**Expected behavior**
Public link displayed and copyable.

### Information about your polls installation
* Version 1.7.4
* Installed through regular apps channel, upgraded but I don't remember for how long.

### Information about your Instance of Nextcloud
**Nextcloud version:** 21

I'm not including more information because this looks like a clear browser-specific bug.

### Browser log
This is on Firefox 86 in Ubuntu 20.04.

No activity at all in developer console after clicking "Add public link". However there are two XHR requests made:
* POST /apps/polls/poll/1/share: success with 200. I see the public URL there, I was able to copy-paste it and use it successfully.
* GET /apps/polls/poll/1/shares: success with 200. I see the public link there, but it's not displayed in UI.

**Comment by dartcafe** [comment] 2021-03-25 19:47
Related to #1452? Do you run uBlock? Try to disable the filters (https://github.com/nextcloud/polls/issues/1452#issuecomment-795287303) or the plugin for this site.

**Comment by haplo** [comment] 2021-03-26 10:30
> Related to #1452? Do you run uBlock? Try to disable the filters ([#1452 (comment)](https://github.com/nextcloud/polls/issues/1452#issuecomment-795287303)) or the plugin for this site.

You are right, it was uBlock, disabling it for the page made the public links to appear. It also works when clicking on the uBlock button to disable cosmetic filtering for the site, so that's the reason.

I'm surprised because uBlock said "0 (0%) elements blocked" on the page, but it looks like that doesn't include cosmetic filtering. TIL.

**Comment by dartcafe** [comment] 2021-03-27 12:35
Since I am not able to identify the reason, I will close this, too. 
I have a configuration in Firefox with uBlock, Privacy bagder and uMatrix. I tried with different combinations of settings and configurations, but cannot reproduce this behavior.

**Closed by dartcafe** 2021-03-27 12:35 UTC

**Comment by Timvde** [comment] 2021-04-23 14:29
I encountered this issue too today. I tracked it down to the "Fanboy's Annoyance" list, which includes a filter on the CSS class `.share-item`. So by renaming that class, you should be able to by pass the filter.

I can look into providing a patch over the weekend if you are interested.

**Comment by dartcafe** [comment] 2021-04-23 22:50
Thanks for that result of your investigation.

But please try to understand, that I am not willing to change parts of the app, because a third parity application manipulates the DOM and blocks elements just depending on the class name. The problem is not the polls app, the ad blocker or at least the used rules are. This issue cannot result in a task for an app like polls. I would say the blocking list has to be fixed. 

Nevertheless I still belive it should be save for a registered user to disable any ad blockers on a trustworthy platform like nextcloud.

**Comment by dartcafe** [comment] 2021-04-23 23:03
I just took a look into the list. There are thousands of generic filters like 
[...]
##.share-it
##.share-item
##.share-item--google
##.share-item-container
##.share-item-horizontal
##.share-items
##.share-kit__facebook
##.share-kit__instagram
##.share-kit__linkedin
##.share-kit__twitter
##.share-kit__youtube
##.share-label
##.share-launch
##.share-left
##.share-legend
##.share-line
##.share-link
##.share-link-button
##.share-link-container
##.share-link-facebook
##.share-link-twitter
##.share-linkedin
##.share-links
##.share-links--link
##.share-links-footer
##.share-links-label
##.share-list
##.share-list-button-box
##.share-list-container
##.share-mail
[...]

It can`t be right, that this filter lists define, which class names a programmer is allowed to use and which are not.

**Comment by haplo** [comment] 2021-04-26 07:34
I just wanted to say I completely agree with @dartcafe, this is a bug with the ad-blocking filter list, so if anything it must be fixed there.
