### ISSUE TITLE
Beta 1 creates bug preventing to access NC Administrator Settings 

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/polls#2670] opened 2022-11-17 11:02 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

If you activate the beta 1, then there is no way to access NC administrator settings anymore:

Interner Serverfehler

Der Server konnte die Anfrage nicht fertig stellen.
Sollte dies erneut auftreten, senden Sie bitte die nachfolgenden technischen Einzelheiten an Ihren Server-Administrator.
Weitere Details können im Server-Protokoll gefunden werden.
Technische Details

Entfernte Adresse: 2a02:26f7:ec44:6604:0:2e8b:7380:c0ec
Anfragekennung: 94Lz5fmLSak30tlRbWrs

### What did you expect, how polls should behave instead?

Being able to access administrator settings

### What steps does it need to replay this bug?

1. Install/activate app from app store
2. Go to NC administrator settings

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [ ] Linux
- [X] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 8.0

### Database engine

MySQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by mkrecek234** [comment] 2022-11-17 11:05
Can only see this error in NC log:

[index] Fehler: RuntimeException: image not found: image:polls-black.svg webroot: serverroot:/home//www//cloud at <<closure>>

 0. /home//www/habelschwerdtde/cloud/apps/polls/lib/Settings/PersonalSection.php line 55
    OC\URLGenerator->imagePath()
 1. /home//www//cloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 94
    OCA\Polls\Settings\PersonalSection->getIcon()
 2. /home//www//cloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 112
    OCA\Settings\Controller\AdminSettingsController->formatSections()
 3. /home//www//cloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 62
    OCA\Settings\Controller\AdminSettingsController->formatPersonalSections()
 4. /home//www//cloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 148
    OCA\Settings\Controller\AdminSettingsController->getNavigationParameters()
 5. /home//www//cloud/apps/settings/lib/Controller/AdminSettingsController.php line 68
    OCA\Settings\Controller\AdminSettingsController->getIndexResponse()
 6. /home//www//cloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AdminSettingsController->index()
 7. /home//www//cloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
 8. /home//www//cloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
 9. /home//www//cloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
10. /home//www//cloud/lib/base.php line 1047
    OC\Route\Router->match()
11. /home//www//cloud/index.php line 36
    OC::handleRequest()

GET /settings/admin/overview
from 2a02:26f7:ec44:6604:0:2e8b:7380:c0ec by nxadmin at 2022-11-17T10:59:58+00:00

**Comment by dartcafe** [comment] 2022-11-17 22:42
Thanks for testing. I will inspect this. Some other issues were found and fixed in #2671

**Comment by dartcafe** [comment] 2022-11-17 22:44
Pleas try to clear the cache, this issue is weird, since polls-black.svg is not referenced anymore inside the code.

**Comment by mkrecek234** [comment] 2022-11-18 10:15
Clearing the cache resolved the issue.

**Comment by dartcafe** [comment] 2022-11-18 20:34
Great. So I think, we can close this. Thanks for looking into the beta anyways.

**Closed by dartcafe** 2022-11-18 20:34 UTC
Labels: bug, investigate

**Comment by gsedej** [comment] 2023-01-25 16:30
The issue re-appared with update today on nc25, poll version 4.1.2
(it does say it's not stable)

```
$ sudo find /var/www/html/ -name polls-black.svg
$ sudo find /var/www/html/ -name polls.svg
/var/www/html/nextcloud/apps/polls/img/polls.svg

```
```
{"reqId":"GfDdk2jWwPqUyb7M9InD",
"level":3,
"time":"2023-01-25T14:12:19+00:00",
"remoteAddr":"164.8.19.99",
"user":"jurij",
"app":"no app in context",
"method":"GET",
"url":"/ocs/v2.php/apps/notifications/api/v2/notifications",
"message":"image not found: image:polls-black.svg webroot: serverroot:/var/www/html/nextcloud",
"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0",
"version":"25.0.3.2",
"exception":{"Exception":"RuntimeException",
"Message":"image not found: image:polls-black.svg webroot: serverroot:/var/www/html/nextcloud",
"Code":0,
"Trace":[{"file":"/var/www/html/nextcloud/apps/polls/lib/Notification/Notifier.php",
"line":111,
"function":"imagePath",
"class":"OC\\URLGenerator",
"type":"->"},
{"file":"/var/www/html/nextcloud/lib/private/Notification/Manager.php",
"line":368,
"function":"prepare",
"class":"OCA\\Polls\\Notification\\Notifier",
"type":"->"},
{"file":"/var/www/html/nextcloud/apps/notifications/lib/Controller/EndpointController.php",
"line":111,
"function":"prepare",
"class":"OC\\Notification\\Manager",
"type":"->"},
{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
"line":225,
"function":"listNotifications",
"class":"OCA\\Notifications\\Controller\\EndpointController",
"type":"->"},
{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
"line":133,
"function":"executeController",
"class":"OC\\AppFramework\\Http\\Dispatcher",
"type":"->"},
{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php",
"line":172,
"function":"dispatch",
"class":"OC\\AppFramework\\Http\\Dispatcher",
"type":"->"},
{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php",
"line":298,
"function":"main",
"class":"OC\\AppFramework\\App",
"type":"::"},
{"file":"/var/www/html/nextcloud/ocs/v1.php",
"line":63,
"function":"match",
"class":"OC\\Route\\Router",
"type":"->"},
{"file":"/var/www/html/nextcloud/ocs/v2.php",
"line":23,
"args":["/var/www/html/nextcloud/ocs/v1.php"],
"function":"require_once"}],
"File":"/var/www/html/nextcloud/lib/private/URLGenerator.php",
"Line":265,
"CustomMessage":"--"}}
 
```

**Comment by dartcafe** [comment] 2023-01-25 21:51
@gsedej I updated 4 productive instances, but cannot reproduce that.
Please make sure, there is no caching issue on the server. Otherwise please open another issue for that.

**Comment by dartcafe** [comment] 2023-01-25 21:51
> (it does say it's not stable)

Who/what says not stable?

**Comment by gsedej** [comment] 2023-01-25 22:13
https://apps.nextcloud.com/apps/polls
Sorry, i saw a red text mentioning unstable, but now i realized there are different versions.

![slika](https://user-images.githubusercontent.com/6927198/214702320-b450119f-89da-46ea-801e-b2af103bc6aa.png)

Regarding caching - I was not able to determine correct way to clear app cache for nextcloud. The system is in production mode and was not willing to risk testing different options. The bug did lock me out of some administration settings. "systemctl restart apache2" helped (is this the way to clean cache?)

Anyway, thank you for hard work with polls app. it's really good!

_btw - it was quite hard to find the the this issue - google and duckduckgo didn't find it, had to manually search in this github_
