### ISSUE TITLE
Cannot create new poll and not access old polls.

### ISSUE THREAD

**Issue by freiheitsnetz** [nextcloud/polls#2862] opened 2023-04-16 20:17 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

After updating to Polls 5.0.0 I can not create any new polls and don't see any old polls. The left side navigation does miss some items. It only has the items "relevant", "participated", "all polls" and "closed polls".  In the lower part it only has "administration" and "polls settings". All items do not list any polls although there must be some. Especially there is no button to create a new poll.

### What did you expect, how polls should behave instead?

Should be able to create polls and list and participate normally.

### What steps does it need to replay this bug?

1. Updated from last 4 release to 5.0.0.
2. Click on the polls app and try to use it normally.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Affected polls version

5.0.0

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [X] Linux
- [ ] MacOs
- [ ] iOS
- [X] Android
- [ ] Other/Don't know

### Add your browser log here

```shell
GET
scheme	https
host	cloud.xxxxx.xx
filename /apps/polls/polls
time	1681673867923
Address xxx.xxx.xxx.xxx:443
Status 500
Internal Server Error
Version HTTP/2


Remote Address: xxxxxxxxxx
Request ID: rm986FDXspk2vBRfJ30b

Transferred 4.85 kB (3.95 kB size)
Referrer Policy no-referrer
```

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 8.1

### Database engine

PostgreSQL

### Database Engine version or other Database

PostgreSQL 12

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
[16/Apr/2023:19:55:30 +0000] "GET /apps/polls/administration/polls?time=1681674929154 HTTP/1.1" 200 5561 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"
[16/Apr/2023:19:55:30 +0000] "GET /apps/polls/polls?time=1681674929150 HTTP/1.1" 500 4853 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"
[16/Apr/2023:19:55:30 +0000] "GET /custom_apps/polls/js/polls-node_modules_vue-material-design-icons_AlertCircle_vue-node_modules_vue-material-design-icons-2b6ce6.js.map?v=38e2d42c158916c3a8c9 HTTP/1.1" 200 6927 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"
[16/Apr/2023:19:55:30 +0000] "GET /custom_apps/polls/js/polls-src_js_components_Settings_UserSettings_FeatureSettings_vue.js.map?v=6ad1e5debf214435f40b HTTP/1.1" 200 2846 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"


{"reqId":"rm986FDXspk2vBRfJ30b","level":3,"time":"2023-04-16T19:55:30+00:00","remoteAddr":"xxxxxxxxxx","user":"xxxxxxxx","app":"index","method":"GET","url":"/index.phps/polls?time=1681674929150","message":"Cannot assign null to property OCA\\Polls\\Db\\Share::$emailAddress of type string in file '/var/www/html/lib/public/AppFramework/Db/Entity.php' line 134","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0","version":"25.0.5.1","exception":{"Exception":"Exception","Message":"Cannot assign null to property OCA\\Polls\\Db\\Share::$emailAddress of type string in file '/var/www/html/lib/public/AppFramework/Db/Entity.php' line 134","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Polls\\Controller\\PollController"],"list"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Polls\\Controller\\PollController","list",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["polls.poll.list"]]},{"file":"/var/www/html/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/polls/polls"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"Cannot assign null to property OCA\\Polls\\Db\\Share::$emailAddress of type string","Code":0,"Trace":[{"file":"/var/www/html/lib/public/AppFramework/Db/Entity.php","line":165,"function":"setter","class":"OCP\\AppFramework\\Db\\Entity","type":"->","args":["emailAddress",[null]]},{"file":"/var/www/html/lib/public/AppFramework/Db/Entity.php","line":73,"function":"__call","class":"OCP\\AppFramework\\Db\\Entity","type":"->","args":["setEmailAddress",[null]]},{"file":"/var/www/html/lib/public/AppFramework/Db/QBMapper.php","line":322,"function":"fromRow","class":"OCP\\AppFramework\\Db\\Entity","type":"::","args":[[7,"sfZHsiHx2abEedTC","public",7,"sfZHsiHx2abEedTC","And 5 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/AppFramework/Db/QBMapper.php","line":340,"function":"mapRowToEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->","args":[[7,"sfZHsiHx2abEedTC","public",7,"sfZHsiHx2abEedTC","And 5 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/custom_apps/polls/lib/Db/ShareMapper.php","line":75,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->","args":[["OC\\DB\\QueryBuilder\\QueryBuilder"]]},{"file":"/var/www/html/custom_apps/polls/lib/Model/Acl.php","line":339,"function":"findByPoll","class":"OCA\\Polls\\Db\\ShareMapper","type":"->","args":[7]},{"file":"/var/www/html/custom_apps/polls/lib/Model/Acl.php","line":396,"function":"getIsDelegatedAdmin","class":"OCA\\Polls\\Model\\Acl","type":"->","args":[]},{"file":"/var/www/html/custom_apps/polls/lib/Model/Acl.php","line":408,"function":"getAllowEditPoll","class":"OCA\\Polls\\Model\\Acl","type":"->","args":[]},{"file":"/var/www/html/custom_apps/polls/lib/Model/Acl.php","line":174,"function":"getAllowAccessPoll","class":"OCA\\Polls\\Model\\Acl","type":"->","args":[]},{"file":"/var/www/html/custom_apps/polls/lib/Model/Acl.php","line":190,"function":"getIsAllowed","class":"OCA\\Polls\\Model\\Acl","type":"->","args":["view"]},{"file":"/var/www/html/custom_apps/polls/lib/Model/Acl.php","line":116,"function":"request","class":"OCA\\Polls\\Model\\Acl","type":"->","args":["view"]},{"file":"/var/www/html/custom_apps/polls/lib/Service/PollService.php","line":80,"function":"setPollId","class":"OCA\\Polls\\Model\\Acl","type":"->","args":[7]},{"file":"/var/www/html/custom_apps/polls/lib/Controller/PollController.php","line":57,"function":"list","class":"OCA\\Polls\\Service\\PollService","type":"->","args":[]},{"file":"/var/www/html/custom_apps/polls/lib/Controller/BaseController.php","line":55,"function":"OCA\\Polls\\Controller\\{closure}","class":"OCA\\Polls\\Controller\\PollController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/polls/lib/Controller/PollController.php","line":61,"function":"response","class":"OCA\\Polls\\Controller\\BaseController","type":"->","args":[["Closure"]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"list","class":"OCA\\Polls\\Controller\\PollController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Polls\\Controller\\PollController"],"list"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Polls\\Controller\\PollController"],"list"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Polls\\Controller\\PollController","list",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["polls.poll.list"]]},{"file":"/var/www/html/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/polls/polls"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/public/AppFramework/Db/Entity.php","Line":134},"CustomMessage":"--"}}
```

### Additional environment informations

Nextcloud is running as docker image

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxxxxx.xxx"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.xxxxxx.xxx",
        "overwritehost": "cloud.xxxxxxx.xxx",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "dbtype": "pgsql",
        "version": "25.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "remember_login_cookie_lifetime": 432000,
        "session_lifetime": 43200,
        "session_keepalive": true,
        "auto_logout": false,
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "app_install_overwrite": [
            "files_retention",
            "files_trackdownloads",
            "apporder",
            "impersonate",
            "files_texteditor",
            "talk_simple_poll"
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - announcementcenter: 6.5.1
  - apporder: 0.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.3
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.1
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.2.0
  - groupfolders: 13.1.2
  - impersonate: 1.12.0
  - keeweb: 0.6.12
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - polls: 5.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.16.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.5
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - talk_simple_poll: 1.3.1
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - encryption: 2.3.0
  - files_external: 1.6.0
  - user_ldap: 1.5.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional Information

I've seen the issue about missing email addresses. But all users (including myself) have valid email addresses.

**Comment by loelkes** [comment] 2023-04-17 02:48
Duplicate of #2852

**Comment by freiheitsnetz** [comment] 2023-04-17 08:28
Thanks @loelkes 
As the title of #2852 states something with email addresses I did not follow the discussion till the end. As you statet it does not seem to have something to do with the email addresses.

I updated to 5.0.1 and the issue still persists.

**Comment by evh-mh** [comment] 2023-04-17 09:15
Same issue here. 
NC 25.0.5
Polls 5.0.0
All users do have valid email-Adresses.

**Comment by dartcafe** [comment] 2023-04-17 10:00
Thanks. There are still some nullish attributes possible, where they should not be or at least get intercepted. Will fix that until this evening.

**Comment by loelkes** [comment] 2023-04-17 17:18
> Thanks @loelkes As the title of #2852 states something with email addresses I did not follow the discussion till the end. As you statet it does not seem to have something to do with the email addresses.

It has all to do with E-Mail addresses, just not on the "User side" but rather internally. If you access the poll through a share the app tries to map you with an existing user. If you access through a public share link there's no equivalent user and the mapping fails since.

**Comment by dartcafe** [comment] 2023-04-17 18:39
Ah, no the problem is, that the database allows some nullish attributes and if they are null the corresponding classes crash. I simply did not give enough attention to it, when fixing the initial bug.

**Closed** 2023-04-17 20:52 UTC
Labels: bug
