### ISSUE TITLE
Can't restrict poll access to a group

### ISSUE THREAD

**Issue by osfrance** [nextcloud/polls#547] opened 2019-03-12 13:43 UTC
Hi all, 
I use v0.10.1 and I can't restrict poll access to a group. When I set "share only" I had no options to add a group or user... (cf Screenshot)

![poll](https://user-images.githubusercontent.com/11570186/54204723-1e626b00-44d5-11e9-8b66-02d05ea51340.png)

**Comment by v1r0x** [comment] 2019-03-12 13:55
Duplicate of #532

**Closed by v1r0x** 2019-03-12 13:55 UTC
