### ISSUE TITLE
Search by group displayname

### ISSUE THREAD

**Issue by razorrazor** [nextcloud/polls#1039] opened 2020-08-03 13:43 UTC
Hi there!

I'm using Polls for first time, and I realize that I cannot search a group by its displayname, only by its GID.
Any idea how to workaround this?

Thanks in advance

**Comment by dartcafe** [comment] 2020-08-03 20:17
No workaround. As long as the display name cannot be changed via UI, this has no priority. Additionally, there is no method to search for groups displaynames, only for GIDs. Or I didn't find it. 

See also: https://github.com/nextcloud/server/issues/9209

**Comment by razorrazor** [comment] 2020-08-04 07:05
Some other app, like Group Folders, allows you to search by displayname and GID, and it always shows the displayname. Therefore, I suppose there is a search method implemented.

I tried to modify SystemController.php and I changed the line #135 inside getSiteUsersAndGroups function with:

					'displayName' => $group->getDisplayName()

, but it threw an error.

I still can't fix the behaviour when I search by group displayname from the Details -> Sharing tab... Any idea?

**Comment by dartcafe** [comment] 2020-08-04 17:40
getDisplayName() works. But searching is not providing with the server classes.

**Comment by razorrazor** [comment] 2020-08-05 07:18
In my tests, getDisplayName() only works with $user, but not with $group. It would be nice you can search by group name, because in some scenarios you can get GID as a number, so that this is not as descriptive as displayname.

**Comment by dartcafe** [comment] 2020-08-12 19:53
Which Version of NC do you have? In 19 it works.

**Comment by razorrazor** [comment] 2020-08-13 07:08
My version is 18.0.7. Maybe that's the problem, but I can't update until all my apps do it.
Thank you!

**Comment by razorrazor** [comment] 2020-11-23 12:30
Now I'm using polls 1.6.2 and NC 19.0.4 and problem persists. It's impossible searching by displayname, and sometimes the search is buggy because after 3 or 4 searchs it breaks. Any idea?

**Comment by dartcafe** [comment] 2020-11-23 19:16
Just checked: Since NC20 the search for groups seems to include the display name. In NC19 it does not find any display names. So, I think you have to wait until update to NC20 is possible.

If the search is buggy, please open a new issue and describe your issue, so we can reproduce this.

**Comment by dartcafe** [comment] 2020-12-21 22:24
Closing, because from NC 20 on it works.

**Closed by dartcafe** 2020-12-21 22:24 UTC
Labels: enhancement
