### ISSUE TITLE
Polls are not public accessible 

### ISSUE THREAD

**Issue by Hanzei** [nextcloud/polls#189] opened 2017-10-18 12:24 UTC
### Steps to reproduce
1. Create a public poll
2. Copy the link to the poll
3. Open the link in a other browser while not being logged in into nextcloud

### Expected behaviour
You should see the poll

### Observed behaviour
![screenshot from 2017-10-18 20-01-09](https://user-images.githubusercontent.com/16541325/31744575-9ee7020c-b45f-11e7-8b0b-bb62ccbe2508.png)

### App Version
0.8

### Related Issues
#167

### Server configuration
**Operating system:** Linux

**Web server:** Apache/2.4.6 (CentOS) (fpm-fcgi)

**Database:** mysql 10.1.28

**PHP version:** 7.1.10
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - cgi-fcgi
 - bcmath
 - bz2
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imap
 - intl
 - json
 - exif
 - mcrypt
 - mysqlnd
 - PDO
 - pgsql
 - apcu
 - posix
 - shmop
 - SimpleXML
 - soap
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tidy
 - tokenizer
 - xml
 - xmlwriter
 - xsl
 - mysqli
 - pdo_mysql
 - pdo_pgsql
 - pdo_sqlite
 - wddx
 - xmlreader
 - apc
 - zip
 - Phar
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** update from nc 12.0.2

**Where did you install Nextcloud from:**  tarball

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.6
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.2.4
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.3
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - polls: 0.8.0
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - spreed: 2.0.1
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - twofactor_u2f: 1.3.3
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - comments
 - encryption
 - external
 - federation
 - files_external
 - survey_client
 - systemtags
 - tasks
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "octhrnlkwg4y",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "version": "12.0.3.3",
    "installed": true,
    "default_language": "de",
    "allow_user_to_change_display_name": false,
    "remember_login_cookie_lifetime": 5184000,
    "session_lifetime": 86400,
    "logtimezone": "Europe\/Berlin",
    "maintenance": false,
    "loglevel": 2,
    "htaccess.RewriteBase": "\/",
    "updater.release.channel": "stable",
    "memcache.local": "\\OC\\Memcache\\APCu"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** Linux

### Logs

<details>
        <summary>Web server error log</summary>

```
No interesting logs
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
No interesting logs
```
</details>

<details>
        <summary>Browser log</summary>

```
No interesting logs
```
</details>

**Comment by dartcafe** [comment] 2017-10-18 16:46
I checked this. I cannot reproduce that (Polls 0.8, NC12). 
https://nc12.yagst.de/index.php/apps/polls/poll/uLGUedKanOXQHckP

**Comment by splitt3r** [comment] 2017-10-18 19:51
Same here.

**Comment by Hanzei** [comment] 2017-10-18 21:52
![screenshot from 2017-10-18 20-01-09](https://user-images.githubusercontent.com/16541325/31734479-205b16be-b43f-11e7-98a1-c83c1f48f509.png)
https://cloud.cjf-berlin.de/apps/polls/poll/9F7Cq9HZIgPtGst8

**Comment by dartcafe** [comment] 2017-10-19 04:12
I get this error, if I try to access a public vote, which is restricted to groups. Can you check this?

**Comment by dartcafe** [comment] 2017-10-19 04:13
Sorry, if the access of the app is restricted to named groups, via the app administration.

**Comment by Hanzei** [comment] 2017-10-19 06:49
That is correct. The poll app is restricted to a group.

**Comment by Hanzei** [comment] 2017-10-19 06:54
Is this a nextcloud problem or is it fixable in the poll app?

**Comment by dartcafe** [comment] 2017-10-20 04:35
@juliushaertl Can you say, if it this problem is resolvable via app or is this an issue in the core? 
When an app is restricted to groups, public pages are no longer accessible for users, which are not logged in.

**Comment by dartcafe** [comment] 2017-10-25 15:37
I fear, it is by design. But I will investigate later.

**Comment by juliushaertl** [comment] 2017-10-25 19:46
> Can you say, if this problem is resolvable via app or is this an issue in the core?
When an app is restricted to groups, public pages are no longer accessible for users, which are not logged in.

Looks like a bug in the server. Also doesn't work with gallery limited to specific groups. Mind opening an issue?

**Comment by dartcafe** [comment] 2017-10-25 20:17
OK. Done. I close this here.

**Closed by dartcafe** 2017-10-25 20:17 UTC
Labels: needs info
