### ISSUE TITLE
Error saving vote

### ISSUE THREAD

**Issue by DoctorWkt** [nextcloud/polls#2600] opened 2022-09-21 22:10 UTC
## Votes Cannot Be Recorded for a Public Poll
**Describe the bug**

I have created a public poll using version 3.8.1 of Polls and created several public links. In another browser, I paste one of these public links in and try to choose a poll option. When I do this, I see an "Error saving vote" popup window.

**Steps to reproduce the behavior**
1. Install Polls 3.8.1 in Nextcloud server 24.0.2
2. Create a poll with these attributes: openly accessible, anonymous, results hidden until closed, 4 options, no closing date, proposals disallowed, limit of 1 yes vote per user
3. Create several public links. In each link, do not ask for the user's e-mail address.
4. Copy one of the links to the clipboard, and paste the link into a separate browser.
5. Attempt to choose one poll option.

## Information about your polls installation
**Polls version:** 3.8.1, fresh install, installed from appstore

## Information about your Instance of Nextcloud
**Nextcloud version:** 24.0.2, just the initial set of apps activated

### Server configuration (decide, if you think it is helpful)

**Database:** SQLite 3, PHP 8.1

### Client configuration
**Device:** Linux running Firefox 104 to create the poll, Chromium 102 for the public link.

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>
[index] Error: OCA\Polls\Exceptions\NotAuthorizedException: Error loading share  pIu6MJWMPhpRSSlv at <<closure>>

0. /var/www/wktcloud/apps/polls/lib/Controller/PublicController.php line 133
   OCA\Polls\Model\Acl->setToken()
1. /var/www/wktcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Polls\Controller\PublicController->getPoll()
2. /var/www/wktcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController()
3. /var/www/wktcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
4. /var/www/wktcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
5. /var/www/wktcloud/lib/base.php line 1023
   OC\Route\Router->match()
6. /var/www/wktcloud/index.php line 36
   OC::handleRequest()

GET /wktcloud/index.php/apps/polls/s/%20pIu6MJWMPhpRSSlv/poll?time=1663794798897
from 124.177.9.193 at 2022-09-21T21:12:47+00:00

{"reqId":"kK7BX13dzT5H8hPzNR2H","level":3,"time":"2022-09-21T21:12:47+00:00","remoteAddr":"124.177.9.193","user":"--","app":"index","method":"GET","url":"/wktcloud/index.php/apps/polls/s/%20pIu6MJWMPhpRSSlv/poll?time=1663794798897","message":"Error loading share  pIu6MJWMPhpRSSlv","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36","version":"24.0.2.1","exception":{"Exception":"OCA\\Polls\\Exceptions\\NotAuthorizedException","Message":"Error loading share  pIu6MJWMPhpRSSlv","Code":0,"Trace":[{"file":"/var/www/wktcloud/apps/polls/lib/Controller/PublicController.php","line":133,"function":"setToken","class":"OCA\\Polls\\Model\\Acl","type":"->"},{"file":"/var/www/wktcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getPoll","class":"OCA\\Polls\\Controller\\PublicController","type":"->"},{"file":"/var/www/wktcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/wktcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/wktcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/wktcloud/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/wktcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/wktcloud/apps/polls/lib/Model/Acl.php","Line":134,"CustomMessage":"--"},"id":"632b8b38b11c0"}

</details>

**Comment by dartcafe** [comment] 2022-09-22 05:27
First, I could not reproduce the issue at first tries. The error says, it could not find a poll using the token from the URL.

Please try another public share, because your request URL contains a space at the beginning of the token: 
GET /wktcloud/index.php/apps/polls/s/**%20**pIu6MJWMPhpRSSlv/poll?time=1663794798897

This is strange, because spaces are no valid characters for tokens and it should not exist.

**Comment by dartcafe** [comment] 2022-09-22 05:46
I could reproduce the error, if I add a space at the beginning of the token, changing the database entry by hand.

**Comment by gexat** [comment] 2022-09-23 10:13
have also a problem since update to Pool 3.8.1

**Comment by gexat** [comment] 2022-09-23 10:25
after downgrading to version 3.7.0 everything is working as normal - https://github.com/nextcloud/polls/releases/download/v3.7.0/polls.tar.gz

**Comment by dartcafe** [comment] 2022-09-23 15:13
> have also a problem since update to Pool 3.8.1

I don't understand. You have a problem or the same problem?

**Comment by gexat** [comment] 2022-09-23 15:48
> > have also a problem since update to Pool 3.8.1
> 
> I don't understand. You have a problem or the same problem?

similar, I have created a public poll with version 3.7.0:
10 options
Limit "Yes" votes per user - 1
Limit "Yes" botes per option - 1
hide not available Options
Poll closing date
Use Autoreminder
Never show results

When a user tried to select a option with version 3.8.1  "Error saving vote" popup window shows up - with version 3.7.0 it's working

**Comment by dartcafe** [comment] 2022-09-24 05:42
I am still not able to reproduce the error. Anyone able to share a link to his site, so I can inspect that?
You can upload a text file here: https://nc.yagst.de/s/ff2ExiXQbnnAPJW

**Comment by germanchiefprogrammer** [comment] 2022-09-25 19:12
I have the same problem with version 3.8.1.
The problem is only if an anonymus user click in the poll.
An "logged in user" have no problem with this.

**Comment by dartcafe** [comment] 2022-09-26 05:13
Thanks for the reports, but without further information I am blind.

I need: 
* logs from browser and server
* possibly the relating db entry from oc_polls_shares
* a detailed description of the circumstances from creating the poll

I tried to reproduce the error with 3 instances but no success.

Alternativly access to a machine, where the error occured.

**Comment by germanchiefprogrammer** [comment] 2022-09-26 07:12
Thank you for your answer.
I have an knowledge!

> Thanks for the reports, but without further information I am blind.
> 
> I need:
> 
>     * logs from browser and server
> 
I use an embedded version of nextcloud. I cannot send you logs or db entries because I have only access to the frontend.

> 
>     * a detailed description of the circumstances from creating the poll
> 

I use Nextcloud V24.0.3 and Poll 3.8.1. 
I cannot downgrade the Poll version.

I just create a new poll in nextcloud (with default setting), add two options and one public link.  The poll is private.

The poll works perfect!!!!

If I deactivate the comment-function in the settings of that poll, the problem is there. In this case the anonymus user cannot save his answer. A message appear, that the answer cannot be saved!

With kind regards.

J

**Comment by dartcafe** [comment] 2022-09-26 09:43
> **If I deactivate the comment-function in the settings of that poll, the problem is there. In this case the anonymus user cannot save his answer. A message appear, that the answer cannot be saved!**

Perfect. I can approve! 🙏

**Closed** 2022-09-27 20:16 UTC
Labels: bug

**Comment by dartcafe** [comment] 2022-09-27 20:18
fixed in 3.8.2. See #2608
